(function(m){"object"==typeof exports&&"object"==typeof module?m(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],m):m(CodeMirror)})(function(m){function q(n,l){for(var e=0;e<n.length;e++)l(n[e],e)}function w(n,l){for(var e=0;e<n.length;e++)if(l(n[e],e))return!0;return!1}m.defineMode("dylan",function(n){function l(a,c,b){c.tokenize=b;return b(a,c)}function e(a,c){var b=a.peek();if("'"==b||'"'==b)return a.next(),l(a,c,r(b,"string"));if("/"==b){a.next();
if(a.eat("*"))return l(a,c,x);if(a.eat("/"))return a.skipToEnd(),"comment";a.backUp(1)}else if(/[+\-\d\.]/.test(b)){if(a.match(/^[+-]?[0-9]*\.[0-9]*([esdx][+-]?[0-9]+)?/i)||a.match(/^[+-]?[0-9]+([esdx][+-]?[0-9]+)/i)||a.match(/^[+-]?\d+/))return"number"}else{if("#"==b){a.next();b=a.peek();if('"'==b)return a.next(),l(a,c,r('"',"string"));if("b"==b)return a.next(),a.eatWhile(/[01]/),"number";if("x"==b)return a.next(),a.eatWhile(/[\da-f]/i),"number";if("o"==b)return a.next(),a.eatWhile(/[0-7]/),"number";
if("#"==b)return a.next(),"punctuation";if("["==b||"("==b)return a.next(),"bracket";if(a.match(/f|t|all-keys|include|key|next|rest/i))return"atom";a.eatWhile(/[-a-zA-Z]/);return"error"}if("~"==b)return a.next(),b=a.peek(),"="==b&&(a.next(),b=a.peek(),"="==b&&a.next()),"operator";if(":"==b){a.next();b=a.peek();if("="==b)return a.next(),"operator";if(":"==b)return a.next(),"punctuation"}else{if(-1!="[](){}".indexOf(b))return a.next(),"bracket";if(-1!=".,".indexOf(b))return a.next(),"punctuation";if(a.match("end"))return"keyword"}}for(var h in k)if(k.hasOwnProperty(h)&&
(c=k[h],c instanceof Array&&w(c,function(f){return a.match(f)})||a.match(c)))return y[h];if(/[+\-*\/^=<>&|]/.test(b))return a.next(),"operator";if(a.match("define"))return"def";a.eatWhile(/[\w\-]/);if(t.hasOwnProperty(a.current()))return u[a.current()];if(a.current().match(z))return"variable";a.next();return"variable-2"}function x(a,c){for(var b=!1,h=!1,f=0,g;g=a.next();){if("/"==g&&b)if(0<f)f--;else{c.tokenize=e;break}else"*"==g&&h&&f++;b="*"==g;h="/"==g}return"comment"}function r(a,c){return function(b,
h){for(var f=!1,g,v=!1;null!=(g=b.next());){if(g==a&&!f){v=!0;break}f=!f&&"\\"==g}if(v||!f)h.tokenize=e;return c}}var d={unnamedDefinition:["interface"],namedDefinition:"module library macro C-struct C-union C-function C-callable-wrapper".split(" "),typeParameterizedDefinition:["class","C-subtype","C-mapped-subtype"],otherParameterizedDefinition:["method","function","C-variable","C-address"],constantSimpleDefinition:["constant"],variableSimpleDefinition:["variable"],otherSimpleDefinition:["generic",
"domain","C-pointer-type","table"],statement:"if block begin method case for select when unless until while iterate profiling dynamic-bind".split(" "),separator:"finally exception cleanup else elseif afterwards".split(" "),other:"above below by from handler in instance let local otherwise slot subclass then to keyed-by virtual".split(" "),signalingCalls:"signal error cerror break check-type abort".split(" ")};d.otherDefinition=d.unnamedDefinition.concat(d.namedDefinition).concat(d.otherParameterizedDefinition);
d.definition=d.typeParameterizedDefinition.concat(d.otherDefinition);d.parameterizedDefinition=d.typeParameterizedDefinition.concat(d.otherParameterizedDefinition);d.simpleDefinition=d.constantSimpleDefinition.concat(d.variableSimpleDefinition).concat(d.otherSimpleDefinition);d.keyword=d.statement.concat(d.separator).concat(d.other);var z=RegExp("^[-_a-zA-Z?!*@<>$%]+"),k={symbolKeyword:"[-_a-zA-Z?!*@<>$%]+:",symbolClass:"<[-_a-zA-Z?!*@<>$%]+>",symbolGlobal:"\\*[-_a-zA-Z?!*@<>$%]+\\*",symbolConstant:"\\$[-_a-zA-Z?!*@<>$%]+"},
y={symbolKeyword:"atom",symbolClass:"tag",symbolGlobal:"variable-2",symbolConstant:"variable-3"},p;for(p in k)k.hasOwnProperty(p)&&(k[p]=new RegExp("^"+k[p]));k.keyword=[/^with(?:out)?-[-_a-zA-Z?!*@<>$%]+/];var A={keyword:"keyword",definition:"def",simpleDefinition:"def",signalingCalls:"builtin"},t={},u={};q(["keyword","definition","simpleDefinition","signalingCalls"],function(a){q(d[a],function(c){t[c]=a;u[c]=A[a]})});return{startState:function(){return{tokenize:e,currentIndent:0}},token:function(a,
c){return a.eatSpace()?null:c.tokenize(a,c)},blockCommentStart:"/*",blockCommentEnd:"*/"}});m.defineMIME("text/x-dylan","dylan")});
