version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/" # Directory of pubspec.yaml
    target-branch: "dev"
    schedule:
      interval: "weekly" # daily, weekly, monthly

  - package-ecosystem: "npm"
    directory: "/standalone" # Directory of package.json
    target-branch: "dev"
    schedule:
      interval: "weekly"
