#FIXME: set these to true eventually; will create lots of errors we have to handle
analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
  errors:
    uri_has_not_been_generated: ignore
    hash_and_equals: ignore
    unused_import: ignore
  plugins:
    - over_react
#   exclude:
#     - path/to/excluded/files/**

# rules: https://workiva.github.io/over_react/analyzer_plugin/lints/
over_react:
  errors:
    over_react_required_props: error
    # I'd like the next but it mistakenly says I can do this when I can't, e.g., when using
    # the spread operator, a for loop, or a conditional expression
    over_react_variadic_children: ignore
#    over_react_boilerplate_error: error
#    over_react_incorrect_doc_comment_location: warning
#    over_react_unnecessary_key: info
#    over_react_pseudo_static_lifecycle: ignore

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
