# I forget what this does
#targets:
#  $default:
#    builders:
#      build_web_compilers|dart_source_cleanup:
#        release_options:
#          enabled: false

# for compiling un-minified production code so JS names are familiar
#targets:
#  $default:
#    builders:
#      build_web_compilers|entrypoint:
#        # These are globs for the entrypoints you want to compile.
#        generate_for:
#          - web/**.dart
#        options:
#          compiler: dart2js
#          dart2js_args:
#            - --no-minify

targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
            - -DSCADNANO_PROD=true
#        generate_for:
#          - test/multiplatform/**_test.dart
#          - test/web/**_test.dart
#          - web/**.dart
#          - test/**
      test_html_builder:
        options:
          templates:
            "test/_templates/react_components_test_template.html":
              - "test/components/*_test.dart"
              - "test/middleware_test.dart"

