{
  "version": "0.11.2",
  "grid": "square",
  "geometry": {
    "inter_helix_gap": 1
  },
  "helices": [
    {"grid_position": [0, 0]},
    {"grid_position": [0, 1]},
    {"grid_position": [0, 2]},
    {"grid_position": [0, 3]},
    {"grid_position": [0, 4]},
    {"grid_position": [0, 5]},
    {"grid_position": [0, 6]},
    {"grid_position": [0, 7]},
    {"grid_position": [0, 8]},
    {"grid_position": [0, 9]},
    {"grid_position": [0, 10]},
    {"grid_position": [0, 11]},
    {"grid_position": [0, 12]},
    {"grid_position": [0, 13]},
    {"grid_position": [0, 14]},
    {"grid_position": [0, 15]},
    {"grid_position": [0, 16]},
    {"grid_position": [0, 17]},
    {"grid_position": [0, 18]},
    {"grid_position": [0, 19]},
    {"grid_position": [0, 20]},
    {"grid_position": [0, 21]},
    {"grid_position": [0, 22]},
    {"grid_position": [0, 23]},
    {"grid_position": [0, 24]},
    {"grid_position": [0, 25]},
    {"grid_position": [0, 26]},
    {"grid_position": [0, 27]},
    {"grid_position": [0, 28]},
    {"grid_position": [0, 29]},
    {"grid_position": [0, 30]},
    {"grid_position": [0, 31]}
  ],
  "strands": [
    {
      "color": "#0066cc",
      "is_scaffold": true,
      "domains": [
        {"helix": 31, "forward": false, "start": 0, "end": 112},
        {"helix": 30, "forward": true, "start": 0, "end": 112},
        {"helix": 29, "forward": false, "start": 0, "end": 112},
        {"helix": 28, "forward": true, "start": 0, "end": 112},
        {"helix": 27, "forward": false, "start": 0, "end": 112},
        {"helix": 26, "forward": true, "start": 0, "end": 112},
        {"helix": 25, "forward": false, "start": 0, "end": 112},
        {"helix": 24, "forward": true, "start": 0, "end": 112},
        {"helix": 23, "forward": false, "start": 0, "end": 112},
        {"helix": 22, "forward": true, "start": 0, "end": 112},
        {"helix": 21, "forward": false, "start": 0, "end": 112},
        {"helix": 20, "forward": true, "start": 0, "end": 112},
        {"helix": 19, "forward": false, "start": 0, "end": 112},
        {"helix": 18, "forward": true, "start": 0, "end": 112},
        {"helix": 17, "forward": false, "start": 0, "end": 112},
        {"helix": 16, "forward": true, "start": 0, "end": 112},
        {"helix": 15, "forward": false, "start": 0, "end": 112},
        {"helix": 14, "forward": true, "start": 0, "end": 112},
        {"helix": 13, "forward": false, "start": 0, "end": 112},
        {"helix": 12, "forward": true, "start": 0, "end": 112},
        {"helix": 11, "forward": false, "start": 0, "end": 112},
        {"helix": 10, "forward": true, "start": 0, "end": 112},
        {"helix": 9, "forward": false, "start": 0, "end": 112},
        {"helix": 8, "forward": true, "start": 0, "end": 112},
        {"helix": 7, "forward": false, "start": 0, "end": 112},
        {"helix": 6, "forward": true, "start": 0, "end": 112},
        {"helix": 5, "forward": false, "start": 0, "end": 112},
        {"helix": 4, "forward": true, "start": 0, "end": 112},
        {"helix": 3, "forward": false, "start": 0, "end": 112},
        {"helix": 2, "forward": true, "start": 0, "end": 112},
        {"helix": 1, "forward": false, "start": 0, "end": 112},
        {"helix": 0, "forward": true, "start": 0, "end": 224},
        {"helix": 1, "forward": false, "start": 112, "end": 224},
        {"helix": 2, "forward": true, "start": 112, "end": 224},
        {"helix": 3, "forward": false, "start": 112, "end": 224},
        {"helix": 4, "forward": true, "start": 112, "end": 224},
        {"helix": 5, "forward": false, "start": 112, "end": 224},
        {"helix": 6, "forward": true, "start": 112, "end": 224},
        {"helix": 7, "forward": false, "start": 112, "end": 224},
        {"helix": 8, "forward": true, "start": 112, "end": 224},
        {"helix": 9, "forward": false, "start": 112, "end": 224},
        {"helix": 10, "forward": true, "start": 112, "end": 224},
        {"helix": 11, "forward": false, "start": 112, "end": 224},
        {"helix": 12, "forward": true, "start": 112, "end": 224},
        {"helix": 13, "forward": false, "start": 112, "end": 224},
        {"helix": 14, "forward": true, "start": 112, "end": 224},
        {"helix": 15, "forward": false, "start": 112, "end": 224},
        {"helix": 16, "forward": true, "start": 112, "end": 224},
        {"helix": 17, "forward": false, "start": 112, "end": 224},
        {"helix": 18, "forward": true, "start": 112, "end": 224},
        {"helix": 19, "forward": false, "start": 112, "end": 224},
        {"helix": 20, "forward": true, "start": 112, "end": 224},
        {"helix": 21, "forward": false, "start": 112, "end": 224},
        {"helix": 22, "forward": true, "start": 112, "end": 224},
        {"helix": 23, "forward": false, "start": 112, "end": 224},
        {"helix": 24, "forward": true, "start": 112, "end": 224},
        {"helix": 25, "forward": false, "start": 112, "end": 224},
        {"helix": 26, "forward": true, "start": 112, "end": 224},
        {"helix": 27, "forward": false, "start": 112, "end": 224},
        {"helix": 28, "forward": true, "start": 112, "end": 224},
        {"helix": 29, "forward": false, "start": 112, "end": 224},
        {"helix": 30, "forward": true, "start": 112, "end": 224},
        {"helix": 31, "forward": false, "start": 112, "end": 224}
      ]
    }
  ]
}
