(function(l){"object"==typeof exports&&"object"==typeof module?l(require("../../lib/codemirror"),require("../css/css")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../css/css"],l):l(CodeMirror)})(function(l){l.defineMode("sass",function(t){function e(a){return!a.peek()||a.match(/\s+$/,!1)}function u(a,b){var c=a.peek();if(")"===c)return a.next(),b.tokenizer=g,"operator";if("("===c)return a.next(),a.eatSpace(),"operator";b.tokenizer="'"===c||'"'===c?q(a.next()):q(")",!1);
return"string"}function v(a,b){return function(c,d){if(c.sol()&&c.indentation()<=a)return d.tokenizer=g,g(c,d);b&&c.skipTo("*/")?(c.next(),c.next(),d.tokenizer=g):c.skipToEnd();return"comment"}}function q(a,b){function c(d,m){var h=d.next(),n=d.peek(),z=d.string.charAt(d.pos-2);return"\\"!==h&&n===a||h===a&&"\\"!==z?(h!==a&&b&&d.next(),e(d)&&(m.cursorHalf=0),m.tokenizer=g,"string"):"#"===h&&"{"===n?(m.tokenizer=w(c),d.next(),"operator"):"string"}null==b&&(b=!0);return c}function w(a){return function(b,
c){return"}"===b.peek()?(b.next(),c.tokenizer=a,"operator"):g(b,c)}}function k(a){0==a.indentCount&&(a.indentCount++,a.scopes.unshift({offset:a.scopes[0].offset+t.indentUnit}))}function g(a,b){var c=a.peek();if(a.match("/*"))return b.tokenizer=v(a.indentation(),!0),b.tokenizer(a,b);if(a.match("//"))return b.tokenizer=v(a.indentation(),!1),b.tokenizer(a,b);if(a.match("#{"))return b.tokenizer=w(g),"operator";if('"'===c||"'"===c)return a.next(),b.tokenizer=q(c),"string";if(b.cursorHalf){if("#"===c&&
(a.next(),a.match(/[0-9a-fA-F]{6}|[0-9a-fA-F]{3}/))||a.match(/^-?[0-9\.]+/))return e(a)&&(b.cursorHalf=0),"number";if(a.match(/^(px|em|in)\b/))return e(a)&&(b.cursorHalf=0),"unit";if(a.match(x))return e(a)&&(b.cursorHalf=0),"keyword";if(a.match(/^url/)&&"("===a.peek())return b.tokenizer=u,e(a)&&(b.cursorHalf=0),"atom";if("$"===c)return a.next(),a.eatWhile(/[\w-]/),e(a)&&(b.cursorHalf=0),"variable-2";if("!"===c)return a.next(),b.cursorHalf=0,a.match(/^[\w]+/)?"keyword":"operator";if(a.match(y))return e(a)&&
(b.cursorHalf=0),"operator";if(a.eatWhile(/[\w-]/))return e(a)&&(b.cursorHalf=0),f=a.current().toLowerCase(),A.hasOwnProperty(f)?"atom":B.hasOwnProperty(f)?"keyword":r.hasOwnProperty(f)?(b.prevProp=a.current().toLowerCase(),"property"):"tag";if(e(a))return b.cursorHalf=0,null}else{if("-"===c&&a.match(/^-\w+-/))return"meta";if("."===c){a.next();if(a.match(/^[\w-]+/))return k(b),"qualifier";if("#"===a.peek())return k(b),"tag"}if("#"===c){a.next();if(a.match(/^[\w-]+/))return k(b),"builtin";if("#"===
a.peek())return k(b),"tag"}if("$"===c)return a.next(),a.eatWhile(/[\w-]/),"variable-2";if(a.match(/^-?[0-9\.]+/))return"number";if(a.match(/^(px|em|in)\b/))return"unit";if(a.match(x))return"keyword";if(a.match(/^url/)&&"("===a.peek())return b.tokenizer=u,"atom";if("="===c&&a.match(/^=[\w-]+/))return k(b),"meta";if("+"===c&&a.match(/^\+[\w-]+/))return"variable-3";"@"===c&&a.match("@extend")&&!a.match(/\s*[\w]/)&&1!=b.scopes.length&&b.scopes.shift();if(a.match(/^@(else if|if|media|else|for|each|while|mixin|function)/))return k(b),
"def";if("@"===c)return a.next(),a.eatWhile(/[\w-]/),"def";if(a.eatWhile(/[\w-]/)){if(a.match(/ *: *[\w-\+\$#!\("']/,!1))return f=a.current().toLowerCase(),r.hasOwnProperty(b.prevProp+"-"+f)?"property":r.hasOwnProperty(f)?(b.prevProp=f,"property"):C.hasOwnProperty(f)?"property":"tag";if(a.match(/ *:/,!1))return k(b),b.cursorHalf=1,b.prevProp=a.current().toLowerCase(),"property";a.match(/ *,/,!1)||k(b);return"tag"}if(":"===c){if(a.match(D))return"variable-3";a.next();b.cursorHalf=1;return"operator"}}if(a.match(y))return"operator";
a.next();return null}var p=l.mimeModes["text/css"],r=p.propertyKeywords||{},B=p.colorKeywords||{},A=p.valueKeywords||{},C=p.fontProperties||{},x=RegExp("^true|false|null|auto"),y=RegExp("^\\(|\\)|=|>|<|==|>=|<=|\\+|-|\\!=|/|\\*|%|and|or|not|;|\\{|\\}|:"),D=/^::?[a-zA-Z_][\w\-]*/,f;return{startState:function(){return{tokenizer:g,scopes:[{offset:0,type:"sass"}],indentCount:0,cursorHalf:0,definedVars:[],definedMixins:[]}},token:function(a,b){a.sol()&&(b.indentCount=0);var c=b.tokenizer(a,b),d=a.current();
"@return"!==d&&"}"!==d||1==b.scopes.length||b.scopes.shift();if(null!==c){d=a.pos-d.length+t.indentUnit*b.indentCount;for(var m=[],h=0;h<b.scopes.length;h++){var n=b.scopes[h];n.offset<=d&&m.push(n)}b.scopes=m}b.lastToken={style:c,content:a.current()};return c},indent:function(a){return a.scopes[0].offset},blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//",fold:"indent"}},"css");l.defineMIME("text/x-sass","sass")});
