(function(k){"object"==typeof exports&&"object"==typeof module?k(require("../lib/codemirror")):"function"==typeof define&&define.amd?define(["../lib/codemirror"],k):k(CodeMirror)})(function(k){function A(a,b){return a.line==b.line&&a.ch==b.ch}function B(a){l.push(a);50<l.length&&l.shift()}function H(a){return l[l.length-(a?Math.min(a,1):1)]||""}function t(a,b,c,d,e){null==e&&(e=a.getRange(b,c));"grow"==d&&v&&v.cm==a&&A(b,v.pos)&&a.isClean(v.gen)?l.length?l[l.length-1]+=e:B(e):!1!==d&&B(e);a.replaceRange("",
b,c,"+delete");v="grow"==d?{cm:a,pos:b,gen:a.changeGeneration()}:null}function w(a,b,c){return a.findPosH(b,c,"char",!0)}function x(a,b,c){return a.findPosH(b,c,"word",!0)}function I(a,b,c){return a.findPosV(b,c,"line",a.doc.sel.goalColumn)}function J(a,b,c){return a.findPosV(b,c,"page",a.doc.sel.goalColumn)}function K(a,b,c){var d=b.line,e=a.getLine(d);b=/\S/.test(0>c?e.slice(0,b.ch):e.slice(b.ch));for(var g=a.firstLine(),n=a.lastLine();;){d+=c;if(d<g||d>n)return a.clipPos(m(d-c,0>c?0:null));e=a.getLine(d);
if(/\S/.test(e))b=!0;else if(b)return m(d,0)}}function y(a,b,c){var d=b.line,e=b.ch;b=a.getLine(b.line);for(var g=!1;;){var n=b.charAt(e+(0>c?-1:0));if(n){if(g&&/[!?.]/.test(n))return m(d,e+(0<c?1:0));g||(g=/\w/.test(n));e+=c}else{if(d==(0>c?a.firstLine():a.lastLine()))return m(d,e);b=a.getLine(d+c);if(!/\S/.test(b))return m(d,e);d+=c;e=0>c?b.length:0}}}function q(a,b,c){var d;if(a.findMatchingBracket&&(d=a.findMatchingBracket(b,{strict:!0}))&&d.match&&(d.forward?1:-1)==c)return 0<c?m(d.to.line,d.to.ch+
1):d.to;for(var e=!0;;e=!1){var g=a.getTokenAt(b);d=m(b.line,0>c?g.start:g.end);if(e&&0<c&&g.end==b.ch||!/\w/.test(g.string)){e=a.findPosH(d,c,"char");if(A(d,e))return b;b=e}else return d}}function u(a,b){var c=a.state.emacsPrefix;if(!c)return b?null:1;C(a);return"-"==c?-1:Number(c)}function p(a){var b="string"==typeof a?function(c){c.execCommand(a)}:a;return function(c){var d=u(c);b(c);for(var e=1;e<d;++e)b(c)}}function D(a,b,c,d){var e=u(a);0>e&&(d=-d,e=-e);for(var g=0;g<e;++g){var n=c(a,b,d);if(A(n,
b))break;b=n}return b}function h(a,b){var c=function(d){d.extendSelection(D(d,d.getCursor(),a,b))};c.motion=!0;return c}function r(a,b,c,d){for(var e=a.listSelections(),g,n=e.length;n--;)g=e[n].head,t(a,g,D(a,g,b,c),d)}function E(a,b){if(a.somethingSelected()){for(var c=a.listSelections(),d,e=c.length;e--;)d=c[e],t(a,d.anchor,d.head,b);return!0}}function L(a,b){a.state.emacsPrefix?"-"!=b&&(a.state.emacsPrefix+=b):(a.state.emacsPrefix=b,a.on("keyHandled",M),a.on("inputRead",N))}function M(a,b){a.state.emacsPrefixMap||
O.hasOwnProperty(b)||C(a)}function C(a){a.state.emacsPrefix=null;a.off("keyHandled",M);a.off("inputRead",N)}function N(a,b){var c=u(a);if(1<c&&"+input"==b.origin){b=b.text.join("\n");for(var d="",e=1;e<c;++e)d+=b;a.replaceSelection(d)}}function z(a,b){if("string"!=typeof b||!/^\d$/.test(b)&&"Ctrl-U"!=b)a.removeKeyMap(F),a.state.emacsPrefixMap=!1,a.off("keyHandled",z),a.off("inputRead",z)}function Q(a,b,c){if(a.openDialog){var d=a.openDialog,e=document.createDocumentFragment(),g=document.createElement("input");
g.setAttribute("type","text");g.style.width="10em";e.appendChild(document.createTextNode(b+": "));e.appendChild(g);d.call(a,e,c,{bottom:!0})}else c(prompt(b,""))}function G(a,b){var c=a.getCursor(),d=a.findPosH(c,1,"word");a.replaceRange(b(a.getRange(c,d)),c,d);a.setCursor(d)}function P(a){F[a]=function(b){L(b,a)};R["Ctrl-"+a]=function(b){L(b,a)};O["Ctrl-"+a]=!0}var f=k.commands,m=k.Pos,l=[],v=null,O={"Alt-G":!0,"Ctrl-X":!0,"Ctrl-Q":!0,"Ctrl-U":!0};f.setMark=function(a){a.setCursor(a.getCursor());
a.setExtending(!a.getExtending());a.on("change",function(){a.setExtending(!1)})};f.killRegion=function(a){t(a,a.getCursor("start"),a.getCursor("end"),!0)};f.killLineEmacs=p(function(a){var b=a.getCursor(),c=a.clipPos(m(b.line)),d=a.getRange(b,c);/\S/.test(d)||(d+="\n",c=m(b.line+1,0));t(a,b,c,"grow",d)});f.killRingSave=function(a){B(a.getSelection());a.setExtending(!1);a.setCursor(a.getCursor())};f.yank=function(a){var b=a.getCursor();a.replaceRange(H(u(a)),b,b,"paste");a.setSelection(b,a.getCursor())};
f.yankPop=function(a){var b=a.replaceSelection;1<l.length&&l.pop();var c=H();b.call(a,c,"around","paste")};f.forwardChar=h(w,1);f.backwardChar=h(w,-1);f.deleteChar=function(a){r(a,w,1,!1)};f.deleteForwardChar=function(a){E(a,!1)||r(a,w,1,!1)};f.deleteBackwardChar=function(a){E(a,!1)||r(a,w,-1,!1)};f.forwardWord=h(x,1);f.backwardWord=h(x,-1);f.killWord=function(a){r(a,x,1,"grow")};f.backwardKillWord=function(a){r(a,x,-1,"grow")};f.nextLine=h(I,1);f.previousLine=h(I,-1);f.scrollDownCommand=h(J,-1);
f.scrollUpCommand=h(J,1);f.backwardParagraph=h(K,-1);f.forwardParagraph=h(K,1);f.backwardSentence=h(y,-1);f.forwardSentence=h(y,1);f.killSentence=function(a){r(a,y,1,"grow")};f.backwardKillSentence=function(a){t(a,a.getCursor(),y(a,a.getCursor(),1),"grow")};f.killSexp=function(a){r(a,q,1,"grow")};f.backwardKillSexp=function(a){r(a,q,-1,"grow")};f.forwardSexp=h(q,1);f.backwardSexp=h(q,-1);f.markSexp=function(a){var b=a.getCursor();a.setSelection(D(a,b,q,1),b)};f.transposeSexps=function(a){var b=q(a,
a.getCursor(),-1),c=q(a,b,1),d=q(a,c,1),e=q(a,d,-1);a.replaceRange(a.getRange(e,d)+a.getRange(c,e)+a.getRange(b,c),b,d)};f.backwardUpList=p(function(a){var b=a.getCursor(),c=b.line;b=b.ch;for(var d=[];c>=a.firstLine();){for(var e=a.getLine(c),g=null==b?e.length:b;0<g;)if(b=e.charAt(--g),")"==b)d.push("(");else if("]"==b)d.push("[");else if("}"==b)d.push("{");else if(/[\(\{\[]/.test(b)&&(!d.length||d.pop()!=b))return a.extendSelection(m(c,g));--c;b=null}});f.justOneSpace=function(a){for(var b=a.getCursor(),
c=b.ch,d=b.ch,e=a.getLine(b.line);c&&/\s/.test(e.charAt(c-1));)--c;for(;d<e.length&&/\s/.test(e.charAt(d));)++d;a.replaceRange(" ",m(b.line,c),m(b.line,d))};f.openLine=p(function(a){a.replaceSelection("\n","start")});f.transposeCharsRepeatable=p(function(a){a.execCommand("transposeChars")});f.capitalizeWord=p(function(a){G(a,function(b){var c=b.search(/\w/);return-1==c?b:b.slice(0,c)+b.charAt(c).toUpperCase()+b.slice(c+1).toLowerCase()})});f.upcaseWord=p(function(a){G(a,function(b){return b.toUpperCase()})});
f.downcaseWord=p(function(a){G(a,function(b){return b.toLowerCase()})});f.undoRepeatable=p("undo");f.keyboardQuit=function(a){a.execCommand("clearSearch");a.setExtending(!1);a.setCursor(a.getCursor())};f.newline=p(function(a){a.replaceSelection("\n","end")});f.gotoLine=function(a){var b=u(a,!0);if(null!=b&&0<b)return a.setCursor(b-1);Q(a,"Goto line",function(c){var d;c&&!isNaN(d=Number(c))&&d==(d|0)&&0<d&&a.setCursor(d-1)})};f.indentRigidly=function(a){a.indentSelection(u(a,!0)||a.getOption("indentUnit"))};
f.exchangePointAndMark=function(a){a.setSelection(a.getCursor("head"),a.getCursor("anchor"))};f.quotedInsertTab=p("insertTab");f.universalArgument=function(a){a.state.emacsPrefixMap=!0;a.addKeyMap(F);a.on("keyHandled",z);a.on("inputRead",z)};k.emacs={kill:t,killRegion:E,repeated:p};var R=k.keyMap.emacs=k.normalizeKeyMap({"Ctrl-W":"killRegion","Ctrl-K":"killLineEmacs","Alt-W":"killRingSave","Ctrl-Y":"yank","Alt-Y":"yankPop","Ctrl-Space":"setMark","Ctrl-Shift-2":"setMark","Ctrl-F":"forwardChar","Ctrl-B":"backwardChar",
Right:"forwardChar",Left:"backwardChar","Ctrl-D":"deleteChar",Delete:"deleteForwardChar","Ctrl-H":"deleteBackwardChar",Backspace:"deleteBackwardChar","Alt-F":"forwardWord","Alt-B":"backwardWord","Alt-Right":"forwardWord","Alt-Left":"backwardWord","Alt-D":"killWord","Alt-Backspace":"backwardKillWord","Ctrl-N":"nextLine","Ctrl-P":"previousLine",Down:"nextLine",Up:"previousLine","Ctrl-A":"goLineStart","Ctrl-E":"goLineEnd",End:"goLineEnd",Home:"goLineStart","Alt-V":"scrollDownCommand","Ctrl-V":"scrollUpCommand",
PageUp:"scrollDownCommand",PageDown:"scrollUpCommand","Ctrl-Up":"backwardParagraph","Ctrl-Down":"forwardParagraph","Alt-{":"backwardParagraph","Alt-}":"forwardParagraph","Alt-A":"backwardSentence","Alt-E":"forwardSentence","Alt-K":"killSentence","Ctrl-X Delete":"backwardKillSentence","Ctrl-Alt-K":"killSexp","Ctrl-Alt-Backspace":"backwardKillSexp","Ctrl-Alt-F":"forwardSexp","Ctrl-Alt-B":"backwardSexp","Shift-Ctrl-Alt-2":"markSexp","Ctrl-Alt-T":"transposeSexps","Ctrl-Alt-U":"backwardUpList","Alt-Space":"justOneSpace",
"Ctrl-O":"openLine","Ctrl-T":"transposeCharsRepeatable","Alt-C":"capitalizeWord","Alt-U":"upcaseWord","Alt-L":"downcaseWord","Alt-;":"toggleComment","Ctrl-/":"undoRepeatable","Shift-Ctrl--":"undoRepeatable","Ctrl-Z":"undoRepeatable","Cmd-Z":"undoRepeatable","Ctrl-X U":"undoRepeatable","Shift-Ctrl-Z":"redo","Shift-Alt-,":"goDocStart","Shift-Alt-.":"goDocEnd","Ctrl-S":"findPersistentNext","Ctrl-R":"findPersistentPrev","Ctrl-G":"keyboardQuit","Shift-Alt-5":"replace","Alt-/":"autocomplete",Enter:"newlineAndIndent",
"Ctrl-J":"newline",Tab:"indentAuto","Alt-G G":"gotoLine","Ctrl-X Tab":"indentRigidly","Ctrl-X Ctrl-X":"exchangePointAndMark","Ctrl-X Ctrl-S":"save","Ctrl-X Ctrl-W":"save","Ctrl-X S":"saveAll","Ctrl-X F":"open","Ctrl-X K":"close","Ctrl-X H":"selectAll","Ctrl-Q Tab":"quotedInsertTab","Ctrl-U":"universalArgument",fallthrough:"default"}),F={"Ctrl-G":C};for(k=0;10>k;++k)P(String(k));P("-")});
