(function(y){"object"==typeof exports&&"object"==typeof module?y(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],y):y(CodeMirror)})(function(y){y.defineMode("haxe",function(h,q){function f(a){return{type:a,style:"keyword"}}function D(a,b){for(var d=!1,e;null!=(e=a.next());){if(e==b&&!d)return!0;d=!d&&"\\"==e}}function p(a,b,d){m=a;Q=d;return b}function E(a,b){var d=a.next();if('"'==d||"'"==d)return d=ba(d),b.tokenize=d,d(a,b);if(/[\[\]{}\(\),;:\.]/.test(d))return p(d);
if("0"==d&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),p("number","number");if(/\d/.test(d)||"-"==d&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*(?!\.))?(?:[eE][+\-]?\d+)?/),p("number","number");if(b.reAllowed&&"~"==d&&a.eat(/\//))return D(a,"/"),a.eatWhile(/[gimsu]/),p("regexp","string-2");if("/"==d){if(a.eat("*"))return d=ca,b.tokenize=d,d(a,b);if(a.eat("/"))return a.skipToEnd(),p("comment","comment");a.eatWhile(J);return p("operator",null,a.current())}if("#"==d)return a.skipToEnd(),p("conditional","meta");
if("@"==d)return a.eat(/:/),a.eatWhile(/[\w_]/),p("metadata","meta");if(J.test(d))return a.eatWhile(J),p("operator",null,a.current());if(/[A-Z]/.test(d))return a.eatWhile(/[\w_<>]/),a=a.current(),p("type","variable-3",a);a.eatWhile(/[\w_]/);a=a.current();return(d=R.propertyIsEnumerable(a)&&R[a])&&b.kwAllowed?p(d.type,d.style,a):p("variable","variable",a)}function ba(a){return function(b,d){D(b,a)&&(d.tokenize=E);return p("string","string")}}function ca(a,b){for(var d=!1,e;e=a.next();){if("/"==e&&
d){b.tokenize=E;break}d="*"==e}return p("comment","comment")}function S(a,b,d,e,t,u){this.indented=a;this.column=b;this.type=d;this.prev=t;this.info=u;null!=e&&(this.align=e)}function T(a){for(var b=g.state,d=b.importedtypes;d;d=d.next)if(d.name==a)return;b.importedtypes={name:a,next:b.importedtypes}}function v(){for(var a=arguments.length-1;0<=a;a--)g.cc.push(arguments[a])}function c(){v.apply(null,arguments);return!0}function U(a,b){for(;b;b=b.next)if(b.name==a)return!0;return!1}function F(a){var b=
g.state;b.context?(g.marked="def",U(a,b.localVars)||(b.localVars={name:a,next:b.localVars})):b.globalVars&&!U(a,b.globalVars)&&(b.globalVars={name:a,next:b.globalVars})}function K(){g.state.context||(g.state.localVars=da);g.state.context={prev:g.state.context,vars:g.state.localVars}}function G(){g.state.localVars=g.state.context.vars;g.state.context=g.state.context.prev}function l(a,b){var d=function(){var e=g.state;e.lexical=new S(e.indented,g.stream.column(),a,null,e.lexical,b)};d.lex=!0;return d}
function k(){var a=g.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function n(a){function b(d){return d==a?c():";"==a?v():c(b)}return b}function w(a){return"@"==a?c(V):"var"==a?c(l("vardef"),L,n(";"),k):"keyword a"==a?c(l("form"),r,w,k):"keyword b"==a?c(l("form"),w,k):"{"==a?c(l("}"),K,M,k,G):";"==a?c():"attribute"==a?c(W):"function"==a?c(A):"for"==a?c(l("form"),n("("),l(")"),ea,n(")"),k,w,k):"variable"==a?c(l("stat"),fa):"switch"==a?c(l("form"),
r,l("}","switch"),n("{"),M,k,k):"case"==a?c(r,n(":")):"default"==a?c(n(":")):"catch"==a?c(l("form"),K,n("("),X,n(")"),w,k,G):"import"==a?c(Y,n(";")):"typedef"==a?c(ha):v(l("stat"),r,n(";"),k)}function r(a){return Z.hasOwnProperty(a)||"type"==a?c(x):"function"==a?c(A):"keyword c"==a?c(N):"("==a?c(l(")"),N,n(")"),k,x):"operator"==a?c(r):"["==a?c(l("]"),z(N,"]"),k,x):"{"==a?c(l("}"),z(ia,"}"),k,x):c()}function N(a){return a.match(/[;\}\)\],]/)?v():v(r)}function x(a,b){if("operator"==a&&/\+\+|--/.test(b))return c(x);
if("operator"==a||":"==a)return c(r);if(";"!=a){if("("==a)return c(l(")"),z(r,")"),k,x);if("."==a)return c(ja,x);if("["==a)return c(l("]"),r,n("]"),k,x)}}function W(a){if("attribute"==a)return c(W);if("function"==a)return c(A);if("var"==a)return c(L)}function V(a){if(":"==a||"variable"==a)return c(V);if("("==a)return c(l(")"),z(ka,")"),k,w)}function ka(a){if("variable"==a)return c()}function Y(a,b){if("variable"==a&&/[A-Z]/.test(b.charAt(0)))return T(b),c();if("variable"==a||"property"==a||"."==a||
"*"==b)return c(Y)}function ha(a,b){if("variable"==a&&/[A-Z]/.test(b.charAt(0)))return T(b),c();if("type"==a&&/[A-Z]/.test(b.charAt(0)))return c()}function fa(a){return":"==a?c(k,w):v(x,n(";"),k)}function ja(a){if("variable"==a)return g.marked="property",c()}function ia(a){"variable"==a&&(g.marked="property");if(Z.hasOwnProperty(a))return c(n(":"),r)}function z(a,b){function d(e){return","==e?c(a,d):e==b?c():c(n(b))}return function(e){return e==b?c():v(a,d)}}function M(a){return"}"==a?c():v(w,M)}
function L(a,b){return"variable"==a?(F(b),c(H,aa)):c()}function aa(a,b){if("="==b)return c(r,aa);if(","==a)return c(L)}function ea(a,b){return"variable"==a?(F(b),c(la,r)):v()}function la(a,b){if("in"==b)return c()}function A(a,b){if("variable"==a||"type"==a)return F(b),c(A);if("new"==b)return c(A);if("("==a)return c(l(")"),K,z(X,")"),k,H,w,G)}function H(a){if(":"==a)return c(ma)}function ma(a){if("type"==a||"variable"==a)return c();if("{"==a)return c(l("}"),z(na,"}"),k)}function na(a){if("variable"==
a)return c(H)}function X(a,b){if("variable"==a)return F(b),c(H)}var B=h.indentUnit;h=f("keyword a");var O=f("keyword b"),C=f("keyword c"),oa=f("operator"),P={type:"atom",style:"atom"},I={type:"attribute",style:"attribute"},m=f("typedef"),R={"if":h,"while":h,"else":O,"do":O,"try":O,"return":C,"break":C,"continue":C,"new":C,"throw":C,"var":f("var"),inline:I,"static":I,using:f("import"),"public":I,"private":I,cast:f("cast"),"import":f("import"),macro:f("macro"),"function":f("function"),"catch":f("catch"),
untyped:f("untyped"),callback:f("cb"),"for":f("for"),"switch":f("switch"),"case":f("case"),"default":f("default"),"in":oa,never:f("property_access"),trace:f("trace"),"class":m,"abstract":m,"enum":m,"interface":m,typedef:m,"extends":m,"implements":m,dynamic:m,"true":P,"false":P,"null":P},J=/[+\-*&%=<>!?|]/,Q,Z={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},g={state:null,column:null,marked:null,cc:null},da={name:"this",next:null};G.lex=!0;k.lex=!0;return{startState:function(a){a={tokenize:E,reAllowed:!0,
kwAllowed:!0,cc:[],lexical:new S((a||0)-B,0,"block",!1),localVars:q.localVars,importedtypes:"Int Float String Void Std Bool Dynamic Array".split(" "),context:q.localVars&&{vars:q.localVars},indented:0};q.globalVars&&"object"==typeof q.globalVars&&(a.globalVars=q.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;var d=b.tokenize(a,b);if("comment"==m)return d;b.reAllowed=!("operator"!=m&&
"keyword c"!=m&&!m.match(/^[\[{}\(,;:]$/));b.kwAllowed="."!=m;a:{var e=m,t=Q,u=b.cc;g.state=b;g.stream=a;g.marked=null;g.cc=u;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((u.length?u.pop():w)(e,t)){for(;u.length&&u[u.length-1].lex;)u.pop()();if(g.marked){d=g.marked;break a}if(a="variable"==e)b:{for(a=b.localVars;a;a=a.next)if(a.name==t){a=!0;break b}a=void 0}if(a){d="variable-2";break a}if(e="variable"==e)b:if(/[a-z]/.test(t.charAt(0)))e=!1;else{e=b.importedtypes.length;for(a=
0;a<e;a++)if(b.importedtypes[a]==t){e=!0;break b}e=void 0}if(e){d="variable-3";break a}break a}}return d},indent:function(a,b){if(a.tokenize!=E)return 0;var d=b&&b.charAt(0);a=a.lexical;"stat"==a.type&&"}"==d&&(a=a.prev);var e=a.type,t=d==e;return"vardef"==e?a.indented+4:"form"==e&&"{"==d?a.indented:"stat"==e||"form"==e?a.indented+B:"switch"!=a.info||t?a.align?a.column+(t?0:1):a.indented+(t?0:B):a.indented+(/^(?:case|default)\b/.test(b)?B:2*B)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",
lineComment:"//"}});y.defineMIME("text/x-haxe","haxe");y.defineMode("hxml",function(){return{startState:function(){return{define:!1,inString:!1}},token:function(h,q){var f=h.peek(),D=h.sol();if("#"==f)return h.skipToEnd(),"comment";if(D&&"-"==f)return f="variable-2",h.eat(/-/),"-"==h.peek()&&(h.eat(/-/),f="keyword a"),"D"==h.peek()&&(h.eat(/[D]/),f="keyword c",q.define=!0),h.eatWhile(/[A-Z]/i),f;f=h.peek();0==q.inString&&"'"==f&&(q.inString=!0,h.next());if(1==q.inString)return h.skipTo("'")||h.skipToEnd(),
"'"==h.peek()&&(h.next(),q.inString=!1),"string";h.next();return null},lineComment:"#"}});y.defineMIME("text/x-hxml","hxml")});
