(function(c){"object"==typeof exports&&"object"==typeof module?c(require("../../lib/codemirror"),require("../htmlmixed/htmlmixed"),require("../../addon/mode/overlay")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../htmlmixed/htmlmixed","../../addon/mode/overlay"],c):c(CodeMirror)})(function(c){c.defineMode("django:inner",function(){function d(b,a){if(b.match("{{"))return a.tokenize=p,"tag";if(b.match("{%"))return a.tokenize=n,"tag";if(b.match("{#"))return a.tokenize=q,"comment";
for(;null!=b.next()&&!b.match(/\{[{%#]/,!1););return null}function e(b,a){return function(f,g){!g.escapeNext&&f.eat(b)?g.tokenize=a:(g.escapeNext&&(g.escapeNext=!1),"\\"==f.next()&&(g.escapeNext=!0));return"string"}}function p(b,a){if(a.waitDot){a.waitDot=!1;if("."!=b.peek())return"null";if(b.match(/\.\W+/))return"error";if(b.eat("."))return a.waitProperty=!0,"null";throw Error("Unexpected error while waiting for property.");}if(a.waitPipe){a.waitPipe=!1;if("|"!=b.peek())return"null";if(b.match(/\.\W+/))return"error";
if(b.eat("|"))return a.waitFilter=!0,"null";throw Error("Unexpected error while waiting for filter.");}if(a.waitProperty&&(a.waitProperty=!1,b.match(/\b(\w+)\b/)))return a.waitDot=!0,a.waitPipe=!0,"property";if(a.waitFilter&&(a.waitFilter=!1,b.match(h)))return"variable-2";if(b.eatSpace())return a.waitProperty=!1,"null";if(b.match(/\b\d+(\.\d+)?\b/))return"number";if(b.match("'"))return a.tokenize=e("'",a.tokenize),"string";if(b.match('"'))return a.tokenize=e('"',a.tokenize),"string";if(b.match(/\b(\w+)\b/)&&
!a.foundVariable)return a.waitDot=!0,a.waitPipe=!0,"variable";if(b.match("}}"))return a.waitProperty=null,a.waitFilter=null,a.waitDot=null,a.waitPipe=null,a.tokenize=d,"tag";b.next();return"null"}function n(b,a){if(a.waitDot){a.waitDot=!1;if("."!=b.peek())return"null";if(b.match(/\.\W+/))return"error";if(b.eat("."))return a.waitProperty=!0,"null";throw Error("Unexpected error while waiting for property.");}if(a.waitPipe){a.waitPipe=!1;if("|"!=b.peek())return"null";if(b.match(/\.\W+/))return"error";
if(b.eat("|"))return a.waitFilter=!0,"null";throw Error("Unexpected error while waiting for filter.");}if(a.waitProperty&&(a.waitProperty=!1,b.match(/\b(\w+)\b/)))return a.waitDot=!0,a.waitPipe=!0,"property";if(a.waitFilter&&(a.waitFilter=!1,b.match(h)))return"variable-2";if(b.eatSpace())return a.waitProperty=!1,"null";if(b.match(/\b\d+(\.\d+)?\b/))return"number";if(b.match("'"))return a.tokenize=e("'",a.tokenize),"string";if(b.match('"'))return a.tokenize=e('"',a.tokenize),"string";if(b.match(k))return"operator";
if(b.match(l))return"keyword";var f=b.match(m);if(f)return"comment"==f[0]&&(a.blockCommentTag=!0),"keyword";if(b.match(/\b(\w+)\b/))return a.waitDot=!0,a.waitPipe=!0,"variable";if(b.match("%}"))return a.waitProperty=null,a.waitFilter=null,a.waitDot=null,a.waitPipe=null,a.blockCommentTag?(a.blockCommentTag=!1,a.tokenize=r):a.tokenize=d,"tag";b.next();return"null"}function q(b,a){b.match(/^.*?#\}/)?a.tokenize=d:b.skipToEnd();return"comment"}function r(b,a){if(b.match(/\{%\s*endcomment\s*%\}/,!1))return a.tokenize=
n,b.match("{%"),"tag";b.next();return"comment"}var m="block endblock for endfor true false filter endfilter loop none self super if elif endif as else import with endwith without context ifequal endifequal ifnotequal endifnotequal extends include load comment endcomment empty url static trans blocktrans endblocktrans now regroup lorem ifchanged endifchanged firstof debug cycle csrf_token autoescape endautoescape spaceless endspaceless ssi templatetag verbatim endverbatim widthratio".split(" "),h=
"add addslashes capfirst center cut date default default_if_none dictsort dictsortreversed divisibleby escape escapejs filesizeformat first floatformat force_escape get_digit iriencode join last length length_is linebreaks linebreaksbr linenumbers ljust lower make_list phone2numeric pluralize pprint random removetags rjust safe safeseq slice slugify stringformat striptags time timesince timeuntil title truncatechars truncatechars_html truncatewords truncatewords_html unordered_list upper urlencode urlize urlizetrunc wordcount wordwrap yesno".split(" "),
k="== != < > <= >=".split(" "),l=["in","not","or","and"];m=new RegExp("^\\b("+m.join("|")+")\\b");h=new RegExp("^\\b("+h.join("|")+")\\b");k=new RegExp("^\\b("+k.join("|")+")\\b");l=new RegExp("^\\b("+l.join("|")+")\\b");return{startState:function(){return{tokenize:d}},token:function(b,a){return a.tokenize(b,a)},blockCommentStart:"{% comment %}",blockCommentEnd:"{% endcomment %}"}});c.defineMode("django",function(d){var e=c.getMode(d,"text/html");d=c.getMode(d,"django:inner");return c.overlayMode(e,
d)});c.defineMIME("text/x-django","django")});
