var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var d=0;return function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,h){if(c==Array.prototype||c==Object.prototype)return c;c[d]=h.value;return c};$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<c.length;++d){var h=c[d];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(c,d){var h=$jscomp.propertyToPolyfillSymbol[d];if(null==h)return c[d];h=c[h];return void 0!==h?h:c[d]};
$jscomp.polyfill=function(c,d,h,k){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(c,d,h,k):$jscomp.polyfillUnisolated(c,d,h,k))};$jscomp.polyfillUnisolated=function(c,d,h,k){h=$jscomp.global;c=c.split(".");for(k=0;k<c.length-1;k++){var g=c[k];if(!(g in h))return;h=h[g]}c=c[c.length-1];k=h[c];d=d(k);d!=k&&null!=d&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(c,d,h,k){var g=c.split(".");c=1===g.length;k=g[0];k=!c&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<g.length-1;l++){var n=g[l];if(!(n in k))return;k=k[n]}g=g[g.length-1];h=$jscomp.IS_SYMBOL_NATIVE&&"es6"===h?k[g]:null;d=d(h);null!=d&&(c?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:d}):d!==h&&(void 0===$jscomp.propertyToPolyfillSymbol[g]&&(h=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+h+"$"+g),$jscomp.defineProperty(k,$jscomp.propertyToPolyfillSymbol[g],{configurable:!0,writable:!0,value:d})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(c){if(c)return c;var d=function(l,n){this.$jscomp$symbol$id_=l;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:n})};d.prototype.toString=function(){return this.$jscomp$symbol$id_};var h="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",k=0,g=function(l){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new d(h+(l||"")+"_"+k++,l)};return g},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(c){if(c)return c;c=Symbol("Symbol.iterator");for(var d="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),h=0;h<d.length;h++){var k=$jscomp.global[d[h]];"function"===typeof k&&"function"!=typeof k.prototype[c]&&$jscomp.defineProperty(k.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return c},"es6",
"es3");$jscomp.iteratorPrototype=function(c){c={next:c};c[Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,d){c instanceof String&&(c+="");var h=0,k=!1,g={next:function(){if(!k&&h<c.length){var l=h++;return{value:d(l,c[l]),done:!1}}k=!0;return{done:!0,value:void 0}}};g[Symbol.iterator]=function(){return g};return g};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
(function(c){"object"==typeof exports&&"object"==typeof module?c(require("../../lib/codemirror"),require("../htmlmixed/htmlmixed")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../htmlmixed/htmlmixed"],c):c(CodeMirror)})(function(c){var d={noEndTag:!0,soyState:"param-def"},h={alias:{noEndTag:!0},delpackage:{noEndTag:!0},namespace:{noEndTag:!0,soyState:"namespace-def"},"@attribute":d,"@attribute?":d,"@param":d,"@param?":d,"@inject":d,"@inject?":d,"@state":d,template:{soyState:"templ-def",
variableScope:!0},extern:{soyState:"param-def"},"export":{soyState:"export"},literal:{},msg:{},fallbackmsg:{noEndTag:!0,reduceIndent:!0},select:{},plural:{},let:{soyState:"var-def"},"if":{},javaimpl:{},jsimpl:{},elseif:{noEndTag:!0,reduceIndent:!0},"else":{noEndTag:!0,reduceIndent:!0},"switch":{},"case":{noEndTag:!0,reduceIndent:!0},"default":{noEndTag:!0,reduceIndent:!0},foreach:{variableScope:!0,soyState:"for-loop"},ifempty:{noEndTag:!0,reduceIndent:!0},"for":{variableScope:!0,soyState:"for-loop"},
call:{soyState:"templ-ref"},param:{soyState:"param-ref"},print:{noEndTag:!0},deltemplate:{soyState:"templ-def",variableScope:!0},delcall:{soyState:"templ-ref"},log:{},element:{variableScope:!0},velog:{},"const":{soyState:"const-def"}},k=Object.keys(h).filter(function(g){return!h[g].noEndTag||h[g].reduceIndent});c.defineMode("soy",function(g){function l(b){return b[b.length-1]}function n(b,a,e){if(b.sol()){for(var f=0;f<a.indent&&b.eat(/\s/);f++);if(f)return null}f=b.string;if(e=e.exec(f.substr(b.pos)))b.string=
f.substr(0,b.pos+e.index);e=b.hideFirstChars(a.indent,function(){var m=l(a.localStates);return m.mode.token(b,m.state)});b.string=f;return e}function p(b,a){return{element:a,next:b}}function u(b){b.context&&(b.context.scope&&(b.variables=b.context.scope),b.context=b.context.previousContext)}function w(b,a,e){a:{for(;b;){if(b.element===a){a=!0;break a}b=b.next}a=!1}return a?"variable-2":e?"variable":"variable-2 error"}function v(b,a,e){this.previousContext=b;this.tag=a;this.kind=null;this.scope=e}
function q(b,a){var e;if(b.match(/[[]/))return a.soyState.push("list-literal"),a.context=new v(a.context,"list-literal",a.variables),a.lookupVariables=!1,null;if(b.match(/\bmap(?=\()/))return a.soyState.push("map-literal"),"keyword";if(b.match(/\brecord(?=\()/))return a.soyState.push("record-literal"),"keyword";if(b.match(/([\w]+)(?=\()/))return"variable callee";if(e=b.match(/^["']/))return a.soyState.push("string"),a.quoteKind=e[0],"string";if(b.match(/^[(]/))return a.soyState.push("open-parentheses"),
null;if(b.match(/(null|true|false)(?!\w)/)||b.match(/0x([0-9a-fA-F]{2,})/)||b.match(/-?([0-9]*[.])?[0-9]+(e[0-9]*)?/))return"atom";if(b.match(/(\||[+\-*\/%]|[=!]=|\?:|[<>]=?)/))return"operator";if(e=b.match(/^\$([\w]+)/))return w(a.variables,e[1],!a.lookupVariables);if(e=b.match(/^\w+/))return/^(?:as|and|or|not|in|if)$/.test(e[0])?"keyword":null;b.next();return null}var r=c.getMode(g,"text/plain"),t={html:c.getMode(g,{name:"text/html",multilineTagIndentFactor:2,multilineTagIndentPastTag:!1,allowMissingTagName:!0}),
attributes:r,text:r,uri:r,trusted_resource_uri:r,css:c.getMode(g,"text/css"),js:c.getMode(g,{name:"text/javascript",statementIndent:2*g.indentUnit})};return{startState:function(){return{soyState:[],variables:p(null,"ij"),scopes:null,indent:0,quoteKind:null,context:null,lookupVariables:!0,localStates:[{mode:t.html,state:c.startState(t.html)}]}},copyState:function(b){return{tag:b.tag,soyState:b.soyState.concat([]),variables:b.variables,context:b.context,indent:b.indent,quoteKind:b.quoteKind,lookupVariables:b.lookupVariables,
localStates:b.localStates.map(function(a){return{mode:a.mode,state:c.copyState(a.mode,a.state)}})}},token:function(b,a){var e;switch(l(a.soyState)){case "comment":b.match(/^.*?\*\//)?a.soyState.pop():b.skipToEnd();if(!a.context||!a.context.scope)for(var f=/@param\??\s+(\S+)/g,m=b.current();e=f.exec(m);)a.variables=p(a.variables,e[1]);return"comment";case "string":return e=b.match(/^.*?(["']|\\[\s\S])/),e?e[1]==a.quoteKind&&(a.quoteKind=null,a.soyState.pop()):b.skipToEnd(),"string"}if(!a.soyState.length||
"literal"!=l(a.soyState)){if(b.match(/^\/\*/))return a.soyState.push("comment"),"comment";if(b.match(b.sol()?/^\s*\/\/.*/:/^\s+\/\/.*/))return"comment"}switch(l(a.soyState)){case "templ-def":if(b.match(/^\.?([\w]+(?!\.[\w]+)*)/))return a.soyState.pop(),"def";b.next();return null;case "templ-ref":if(e=b.match(/(\.?[a-zA-Z_][a-zA-Z_0-9]+)+/))return a.soyState.pop(),"."==e[0][0]?"variable-2":"variable";if(e=b.match(/^\$([\w]+)/))return a.soyState.pop(),w(a.variables,e[1],!a.lookupVariables);b.next();
return null;case "namespace-def":if(b.match(/^\.?([\w\.]+)/))return a.soyState.pop(),"variable";b.next();return null;case "param-def":if(b.match(/^\*/))return a.soyState.pop(),a.soyState.push("param-type"),"type";if(e=b.match(/^\w+/))return a.variables=p(a.variables,e[0]),a.soyState.pop(),a.soyState.push("param-type"),"def";b.next();return null;case "param-ref":if(b.match(/^\w+/))return a.soyState.pop(),"property";b.next();return null;case "open-parentheses":return b.match(/[)]/)?(a.soyState.pop(),
null):q(b,a);case "param-type":f=b.peek();if(-1!="}]=>,".indexOf(f))return a.soyState.pop(),null;if("["==f)return a.soyState.push("param-type-record"),null;if("("==f)return a.soyState.push("param-type-template"),null;if("<"==f)return a.soyState.push("param-type-parameter"),null;if(b.match(/^([\w]+|[?])/))return"type";b.next();return null;case "param-type-record":f=b.peek();if("]"==f)return a.soyState.pop(),null;if(b.match(/^\w+/))return a.soyState.push("param-type"),"property";b.next();return null;
case "param-type-parameter":if(b.match(/^[>]/))return a.soyState.pop(),null;if(b.match(/^[<,]/))return a.soyState.push("param-type"),null;b.next();return null;case "param-type-template":if(b.match(/[>]/))return a.soyState.pop(),a.soyState.push("param-type"),null;if(b.match(/^\w+/))return a.soyState.push("param-type"),"def";b.next();return null;case "var-def":if(e=b.match(/^\$([\w]+)/))return a.variables=p(a.variables,e[1]),a.soyState.pop(),"def";b.next();return null;case "for-loop":if(b.match(/\bin\b/))return a.soyState.pop(),
"keyword";if("$"==b.peek())return a.soyState.push("var-def"),null;b.next();return null;case "record-literal":if(b.match(/^[)]/))return a.soyState.pop(),null;if(b.match(/[(,]/))return a.soyState.push("map-value"),a.soyState.push("record-key"),null;b.next();return null;case "map-literal":if(b.match(/^[)]/))return a.soyState.pop(),null;if(b.match(/[(,]/))return a.soyState.push("map-value"),a.soyState.push("map-value"),null;b.next();return null;case "list-literal":return b.match("]")?(a.soyState.pop(),
a.lookupVariables=!0,u(a),null):b.match(/\bfor\b/)?(a.lookupVariables=!0,a.soyState.push("for-loop"),"keyword"):q(b,a);case "record-key":if(b.match(/[\w]+/))return"property";if(b.match(/^[:]/))return a.soyState.pop(),null;b.next();return null;case "map-value":return")"==b.peek()||","==b.peek()||b.match(/^[:)]/)?(a.soyState.pop(),null):q(b,a);case "import":if(b.eat(";"))return a.soyState.pop(),a.indent-=2*g.indentUnit,null;if(b.match(/\w+(?=\s+as\b)/))return"variable";if(e=b.match(/\w+/))return/\b(from|as)\b/.test(e[0])?
"keyword":"def";if(e=b.match(/^["']/))return a.soyState.push("string"),a.quoteKind=e[0],"string";b.next();return null;case "tag":return void 0===a.tag?(f=!0,m=""):m=(f="/"==a.tag[0])?a.tag.substring(1):a.tag,b.match(/^\/?}/)?((m="/}"==b.current())&&!f&&u(a),"/template"==a.tag||"/deltemplate"==a.tag?(a.variables=p(null,"ij"),a.indent=0):a.indent-=g.indentUnit*(m||-1==k.indexOf(a.tag)?2:1),a.soyState.pop(),"keyword"):b.match(/^([\w?]+)(?==)/)?(a.context&&a.context.tag==m&&"kind"==b.current()&&(e=b.match(/^="([^"]+)/,
!1))&&(f=e[1],a.context.kind=f,m=t[f]||t.html,f=l(a.localStates),f.mode.indent&&(a.indent+=f.mode.indent(f.state,"","")),a.localStates.push({mode:m,state:c.startState(m)})),"attribute"):q(b,a);case "template-call-expression":return b.match(/^([\w-?]+)(?==)/)?"attribute":b.eat(">")||b.eat("/>")?(a.soyState.pop(),"keyword"):q(b,a);case "literal":return b.match("{/literal}",!1)?(a.soyState.pop(),this.token(b,a)):n(b,a,/\{\/literal}/);case "export":if(e=b.match(/\w+/)){a.soyState.pop();if("const"==e)return a.soyState.push("const-def"),
"keyword";if("extern"==e)return a.soyState.push("param-def"),"keyword"}else b.next();return null;case "const-def":if(b.match(/^\w+/))return a.soyState.pop(),"def";b.next();return null}if(b.match("{literal}"))return a.indent+=g.indentUnit,a.soyState.push("literal"),a.context=new v(a.context,"literal",a.variables),"keyword";if(e=b.match(/^\{([/@\\]?\w+\??)(?=$|[\s}]|\/[/*])/)){var x=a.tag;a.tag=e[1];f="/"==a.tag[0];var y=!!h[a.tag];m=f?a.tag.substring(1):a.tag;b=h[m];"/switch"!=a.tag&&(a.indent+=((f||
b&&b.reduceIndent)&&"switch"!=x?1:2)*g.indentUnit);a.soyState.push("tag");e=!1;b?(f||b.soyState&&a.soyState.push(b.soyState),b.noEndTag||!y&&f)?f&&(f="extern"==m&&a.context&&"export"==a.context.tag,!a.context||a.context.tag!=m&&!f?e=!0:a.context&&(a.context.kind&&(a.localStates.pop(),f=l(a.localStates),f.mode.indent&&(a.indent-=f.mode.indent(f.state,"",""))),u(a))):a.context=new v(a.context,a.tag,b.variableScope?a.variables:null):f&&(e=!0);return(e?"error ":"")+"keyword"}return b.eat("{")?(a.tag=
"print",a.indent+=2*g.indentUnit,a.soyState.push("tag"),"keyword"):!a.context&&b.sol()&&b.match(/import\b/)?(a.soyState.push("import"),a.indent+=2*g.indentUnit,"keyword"):b.match("<{")?(a.soyState.push("template-call-expression"),a.indent+=2*g.indentUnit,a.soyState.push("tag"),"keyword"):b.match("</>")?(a.indent-=1*g.indentUnit,"keyword"):n(b,a,/\{|\s+\/\/|\/\*/)},indent:function(b,a,e){var f=b.indent,m=l(b.soyState);if("comment"==m)return c.Pass;if("literal"==m)/^\{\/literal}/.test(a)&&(f-=g.indentUnit);
else{if(/^\s*\{\/(template|deltemplate)\b/.test(a))return 0;/^\{(\/|(fallbackmsg|elseif|else|ifempty)\b)/.test(a)&&(f-=g.indentUnit);"switch"!=b.tag&&/^\{(case|default)\b/.test(a)&&(f-=g.indentUnit);/^\{\/switch\b/.test(a)&&(f-=g.indentUnit)}b=l(b.localStates);f&&b.mode.indent&&(f+=b.mode.indent(b.state,a,e));return f},innerMode:function(b){return b.soyState.length&&"literal"!=l(b.soyState)?null:l(b.localStates)},electricInput:/^\s*\{(\/|\/template|\/deltemplate|\/switch|fallbackmsg|elseif|else|case|default|ifempty|\/literal\})$/,
lineComment:"//",blockCommentStart:"/*",blockCommentEnd:"*/",blockCommentContinue:" * ",useInnerComments:!1,fold:"indent"}},"htmlmixed");c.registerHelper("wordChars","soy",/[\w$]/);c.registerHelper("hintWords","soy",Object.keys(h).concat(["css","debugger"]));c.defineMIME("text/x-soy","soy")});
