(function(f){"object"==typeof exports&&"object"==typeof module?f(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],f):f(CodeMirror)})(function(f){f.defineMode("coffeescript",function(t,u){function l(a){return new RegExp("^(("+a.join(")|(")+"))\\b")}function k(a,b){if(a.sol()){null===b.scope.align&&(b.scope.align=!1);var c=b.scope.offset;if(a.eatSpace())return a=a.indentation(),a>c&&"coffee"==b.scope.type?"indent":a<c?"dedent":null;0<c&&n(a,b)}if(a.eatSpace())return null;
c=a.peek();if(a.match("####"))return a.skipToEnd(),"comment";if(a.match("###"))return b.tokenize=v,b.tokenize(a,b);if("#"===c)return a.skipToEnd(),"comment";if(a.match(/^-?[0-9\.]/,!1)){c=!1;a.match(/^-?\d*\.\d+(e[\+\-]?\d+)?/i)&&(c=!0);a.match(/^-?\d+\.\d*/)&&(c=!0);a.match(/^-?\.\d+/)&&(c=!0);if(c)return"."==a.peek()&&a.backUp(1),"number";c=!1;a.match(/^-?0x[0-9a-f]+/i)&&(c=!0);a.match(/^-?[1-9]\d*(e[\+\-]?\d+)?/)&&(c=!0);a.match(/^-?0(?![\dx])/i)&&(c=!0);if(c)return"number"}if(a.match(w))return b.tokenize=
q(a.current(),!1,"string"),b.tokenize(a,b);if(a.match(x)){if("/"!=a.current()||a.match(/^.*\//,!1))return b.tokenize=q(a.current(),!0,"string-2"),b.tokenize(a,b);a.backUp(1)}if(a.match(y)||a.match(z))return"operator";if(a.match(A))return"punctuation";if(a.match(B))return"atom";if(a.match(C)||b.prop&&a.match(r))return"property";if(a.match(D))return"keyword";if(a.match(r))return"variable";a.next();return"error"}function q(a,b,c){return function(d,e){for(;!d.eol();)if(d.eatWhile(/[^'"\/\\]/),d.eat("\\")){if(d.next(),
b&&d.eol())return c}else{if(d.match(a))return e.tokenize=k,c;d.eat(/['"\/]/)}b&&(u.singleLineStringErrors?c="error":e.tokenize=k);return c}}function v(a,b){for(;!a.eol();){a.eatWhile(/[^#]/);if(a.match("###")){b.tokenize=k;break}a.eatWhile("#")}return"comment"}function p(a,b,c){c=c||"coffee";for(var d=0,e=!1,g=null,h=b.scope;h;h=h.prev)if("coffee"===h.type||"}"==h.type){d=h.offset+t.indentUnit;break}"coffee"!==c?(e=null,g=a.column()+a.current().length):b.scope.align&&(b.scope.align=!1);b.scope={offset:d,
type:c,prev:b.scope,align:e,alignOffset:g}}function n(a,b){if(b.scope.prev){if("coffee"===b.scope.type){a=a.indentation();for(var c=!1,d=b.scope;d;d=d.prev)if(a===d.offset){c=!0;break}if(!c)return!0;for(;b.scope.prev&&b.scope.offset!==a;)b.scope=b.scope.prev}else b.scope=b.scope.prev;return!1}}var y=/^(?:->|=>|\+[+=]?|-[\-=]?|\*[\*=]?|\/[\/=]?|[=!]=|<[><]?=?|>>?=?|%=?|&=?|\|=?|\^=?|~|!|\?|(or|and|\|\||&&|\?)=)/,A=/^(?:[()\[\]{},:`=;]|\.\.?\.?)/,r=/^[_A-Za-z$][_A-Za-z$0-9]*/,C=/^@[_A-Za-z$][_A-Za-z$0-9]*/,
z=l("and or not is isnt in instanceof typeof".split(" ")),m="for while loop if unless else switch try catch finally class".split(" "),D=l(m.concat("break by continue debugger delete do in of new return then this @ throw when until extends".split(" ")));m=l(m);var w=/^('{3}|"{3}|['"])/,x=/^(\/{3}|\/)/,B=l("Infinity NaN undefined null true false on off yes no".split(" "));return{startState:function(a){return{tokenize:k,scope:{offset:a||0,type:"coffee",prev:null,align:!1},prop:!1,dedent:0}},token:function(a,
b){var c=null===b.scope.align&&b.scope;c&&a.sol()&&(c.align=!1);var d=b.tokenize(a,b);var e=a.current();"return"===e&&(b.dedent=!0);(("->"===e||"=>"===e)&&a.eol()||"indent"===d)&&p(a,b);var g="[({".indexOf(e);-1!==g&&p(a,b,"])}".slice(g,g+1));m.exec(e)&&p(a,b);"then"==e&&n(a,b);if("dedent"===d&&n(a,b))d="error";else{g="])}".indexOf(e);if(-1!==g){for(;"coffee"==b.scope.type&&b.scope.prev;)b.scope=b.scope.prev;b.scope.type==e&&(b.scope=b.scope.prev)}b.dedent&&a.eol()&&("coffee"==b.scope.type&&b.scope.prev&&
(b.scope=b.scope.prev),b.dedent=!1)}d&&"comment"!=d&&(c&&(c.align=!0),b.prop="punctuation"==d&&"."==a.current());return d},indent:function(a,b){if(a.tokenize!=k)return 0;a=a.scope;var c=b&&-1<"])}".indexOf(b.charAt(0));if(c)for(;"coffee"==a.type&&a.prev;)a=a.prev;b=c&&a.type===b.charAt(0);return a.align?a.alignOffset-(b?1:0):(b?a.prev:a).offset},lineComment:"#",fold:"indent"}});f.defineMIME("application/vnd.coffeescript","coffeescript");f.defineMIME("text/x-coffeescript","coffeescript");f.defineMIME("text/coffeescript",
"coffeescript")});
