(function(f){"object"==typeof exports&&"object"==typeof module?f(require("../../lib/codemirror"),require("../htmlmixed/htmlmixed"),require("../ruby/ruby")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../htmlmixed/htmlmixed","../ruby/ruby"],f):f(CodeMirror)})(function(f){f.defineMode("slim",function(p){function M(a,b,c){var d=function(e,g){g.tokenize=b;return e.pos<a?(e.pos=a,c):g.tokenize(e,g)};return function(e,g){g.tokenize=d;return b(e,g)}}function w(a,b){a.stack={parent:a.stack,
style:"continuation",indented:b,tokenize:a.line};a.line=a.tokenize}function x(a){a.line==a.tokenize&&(a.line=a.stack.tokenize,a.stack=a.stack.parent)}function N(a,b){return function(c,d){x(d);if(c.match(/^\\$/))return w(d,a),"lineContinuation";d=b(c,d);c.eol()&&c.current().match(/(?:^|[^\\])(?:\\\\)*\\$/)&&c.backUp(1);return d}}function O(a,b){return function(c,d){x(d);var e=b(c,d);c.eol()&&c.current().match(/,$/)&&w(d,a);return e}}function y(a,b){return function(c,d){return c.peek()==a&&1==d.rubyState.tokenize.length?
(c.next(),d.tokenize=b,"closeAttributeTag"):q(c,d)}}function k(a){var b,c=function(d,e){if(1==e.rubyState.tokenize.length&&!e.rubyState.context.prev){d.backUp(1);if(d.eatSpace())return e.rubyState=b,e.tokenize=a,a(d,e);d.next()}return q(d,e)};return function(d,e){b=e.rubyState;e.rubyState=f.startState(r);e.tokenize=c;return q(d,e)}}function q(a,b){return r.token(a,b.rubyState)}function C(a,b){if(a.match(/^#\{/))return b.tokenize=y("}",b.tokenize),null;var c=u.token(a,b.htmlState),d=a.current(),e=
d.search(/[^\\]#\{/);-1<e&&(b.tokenize=M(a.pos,b.tokenize,c),a.backUp(d.length-e-1));return c}function P(a){return function(b,c){var d=b.match(/^\\$/)?"lineContinuation":C(b,c);b.eol()&&(c.tokenize=a);return d}}function D(a,b,c){b.stack={parent:b.stack,style:"html",indented:a.column()+c,tokenize:b.line};b.line=b.tokenize=C;return null}function E(a,b){a.skipToEnd();return b.stack.style}function m(a,b){if(a.eat(b.stack.endQuote))return b.line=b.stack.line,b.tokenize=b.stack.tokenize,b.stack=b.stack.parent,
null;if(a.match(Q))return b.tokenize=R,"slimAttribute";a.next();return null}function R(a,b){return a.match(/^==?/)?(b.tokenize=S,null):m(a,b)}function S(a,b){var c=a.peek();return'"'==c||"'"==c?(b.tokenize=F(c,"string",!0,!1,m),a.next(),b.tokenize(a,b)):"["==c?k(m)(a,b):a.match(/^(true|false|nil)\b/)?(b.tokenize=m,"keyword"):k(m)(a,b)}function T(a,b){if(a.match(/^#\{/))return b.tokenize=y("}",b.tokenize),null;var c=new f.StringStream(a.string.slice(b.stack.indented),a.tabSize);c.pos=a.pos-b.stack.indented;
c.start=a.start-b.stack.indented;c.lastColumnPos=a.lastColumnPos-b.stack.indented;c.lastColumnValue=a.lastColumnValue-b.stack.indented;var d=b.subMode.token(c,b.subState);a.pos=c.pos+b.stack.indented;return d}function U(a,b){b.stack.indented=a.column();b.line=b.tokenize=T;return b.tokenize(a,b)}function V(a,b){a.skipToEnd();return"slimDoctype"}function W(a,b){if("<"==a.peek())return(b.tokenize=P(b.tokenize))(a,b);if(a.match(/^[|']/))return D(a,b,1);if(a.match(/^\/(!|\[\w+])?/))return b.stack={parent:b.stack,
style:"comment",indented:b.indented+1,tokenize:b.line},b.line=E,E(a,b);if(a.match(/^(-|==?[<>]?)/))return b.tokenize=N(a.column(),O(a.column(),q)),"slimSwitch";if(a.match(/^doctype\b/))return b.tokenize=V,"keyword";var c=a.match(X);if(c){a=c[1];if(z.hasOwnProperty(a))a=z[a];else{c=G[a];var d=f.mimeModes[c];c=d?f.getMode(p,d):(d=f.modes[c])?d(p,{name:c}):f.getMode(p,"null");a=z[a]=c}c=f.startState(a);b.subMode=a;b.subState=c;b.stack={parent:b.stack,style:"sub",indented:b.indented+1,tokenize:b.line};
b.line=b.tokenize=U;return"slimSubmode"}return A(a,b)}function B(a,b){return b.startOfLine?W(a,b):A(a,b)}function A(a,b){return a.eat("*")?(b.tokenize=k(H),null):a.match(Y)?(b.tokenize=H,"slimTag"):t(a,b)}function H(a,b){return a.match(/^(<>?|><?)/)?(b.tokenize=t,null):t(a,b)}function t(a,b){return a.match(Z)?(b.tokenize=t,"slimId"):a.match(aa)?(b.tokenize=t,"slimClass"):l(a,b)}function l(a,b){return a.match(/^([\[\{\(])/)?(b.stack={parent:b.stack,style:"wrapper",indented:b.indented+1,tokenize:l,
line:b.line,endQuote:ba[RegExp.$1]},b.line=b.tokenize=m,null):a.match(ca)?(b.tokenize=da,"slimAttribute"):"*"==a.peek()?(a.next(),b.tokenize=k(I),null):I(a,b)}function da(a,b){return a.match(/^==?/)?(b.tokenize=ea,null):l(a,b)}function ea(a,b){var c=a.peek();return'"'==c||"'"==c?(b.tokenize=F(c,"string",!0,!1,l),a.next(),b.tokenize(a,b)):"["==c?k(l)(a,b):":"==c?k(J)(a,b):a.match(/^(true|false|nil)\b/)?(b.tokenize=l,"keyword"):k(l)(a,b)}function J(a,b){a.backUp(1);if(a.match(/^[^\s],(?=:)/))return b.tokenize=
k(J),null;a.next();return l(a,b)}function F(a,b,c,d,e){return function(g,n){x(n);var h=0==g.current().length;if(g.match(/^\\$/,h)){if(!h)return b;w(n,n.indented);return"lineContinuation"}if(g.match(/^#\{/,h)){if(!h)return b;n.tokenize=y("}",n.tokenize);return null}h=!1;for(var v;null!=(v=g.next());){if(v==a&&(d||!h)){n.tokenize=e;break}if(c&&"#"==v&&!h&&g.eat("{")){g.backUp(2);break}h=!h&&"\\"==v}g.eol()&&h&&g.backUp(1);return b}}function I(a,b){if(a.match(/^==?/))return b.tokenize=q,"slimSwitch";
if(a.match(/^\/$/))return b.tokenize=B,null;if(a.match(/^:/))return b.tokenize=A,"slimSwitch";D(a,b,0);return b.tokenize(a,b)}var u=f.getMode(p,{name:"htmlmixed"}),r=f.getMode(p,"ruby"),z={html:u,ruby:r},G={ruby:"ruby",javascript:"javascript",css:"text/css",sass:"text/x-sass",scss:"text/x-scss",less:"text/x-less",styl:"text/x-styl",coffee:"coffeescript",asciidoc:"text/x-asciidoc",markdown:"text/x-markdown",textile:"text/x-textile",creole:"text/x-creole",wiki:"text/x-wiki",mediawiki:"text/x-mediawiki",
rdoc:"text/x-rdoc",builder:"text/x-builder",nokogiri:"text/x-nokogiri",erb:"application/x-erb"},X=function(a){var b=[],c;for(c in a)b.push(c);return new RegExp("^("+b.join("|")+"):")}(G),K={commentLine:"comment",slimSwitch:"operator special",slimTag:"tag",slimId:"attribute def",slimClass:"attribute qualifier",slimAttribute:"attribute",slimSubmode:"keyword special",closeAttributeTag:null,slimDoctype:null,lineContinuation:null},ba={"{":"}","[":"]","(":")"},Y=RegExp("^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd](?::[_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\\-0-9\u00b7\u0300-\u036f\u203f-\u2040]|[_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*)"),
ca=RegExp("^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd][:\\._a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*(?=\\s*=)"),Q=RegExp("^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd][:\\._a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*"),
aa=/^\.-?[_a-zA-Z]+[\w\-]*/,Z=/^#[_a-zA-Z]+[\w\-]*/,L={startState:function(){var a=f.startState(u),b=f.startState(r);return{htmlState:a,rubyState:b,stack:null,last:null,tokenize:B,line:B,indented:0}},copyState:function(a){return{htmlState:f.copyState(u,a.htmlState),rubyState:f.copyState(r,a.rubyState),subMode:a.subMode,subState:a.subMode&&f.copyState(a.subMode,a.subState),stack:a.stack,last:a.last,tokenize:a.tokenize,line:a.line}},token:function(a,b){if(a.sol())for(b.indented=a.indentation(),b.startOfLine=
!0,b.tokenize=b.line;b.stack&&b.stack.indented>b.indented&&"slimSubmode"!=b.last;)b.line=b.tokenize=b.stack.tokenize,b.stack=b.stack.parent,b.subMode=null,b.subState=null;if(a.eatSpace())return null;a=b.tokenize(a,b);b.startOfLine=!1;a&&(b.last=a);return K.hasOwnProperty(a)?K[a]:a},blankLine:function(a){if(a.subMode&&a.subMode.blankLine)return a.subMode.blankLine(a.subState)},innerMode:function(a){return a.subMode?{state:a.subState,mode:a.subMode}:{state:a,mode:L}}};return L},"htmlmixed","ruby");
f.defineMIME("text/x-slim","slim");f.defineMIME("application/x-slim","slim")});
