name: scadnano_reducers
description: Reducers for scadnano - extracted to a separate package to optimize built_value code generation caching.

environment:
  sdk: '>=3.11.0 <4.0.0'   # see issue #1104; must match the root pubspec

resolution: workspace

dependencies:
  scadnano_state_actions:
    path: ../scadnano_state_actions
  built_collection: ^5.1.1
  color: ^3.0.0
  collection: ^1.15.0-nullsafety.4
  redux: ^5.0.0
