var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(g,p,n){g instanceof String&&(g=String(g));for(var r=g.length,q=0;q<r;q++){var y=g[q];if(p.call(n,y,q,g))return{i:q,v:y}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,p,n){if(g==Array.prototype||g==Object.prototype)return g;g[p]=n.value;return g};$jscomp.getGlobal=function(g){g=["object"==typeof globalThis&&globalThis,g,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<g.length;++p){var n=g[p];if(n&&n.Math==Math)return n}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(g,p){var n=$jscomp.propertyToPolyfillSymbol[p];if(null==n)return g[p];n=g[n];return void 0!==n?n:g[p]};
$jscomp.polyfill=function(g,p,n,r){p&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(g,p,n,r):$jscomp.polyfillUnisolated(g,p,n,r))};$jscomp.polyfillUnisolated=function(g,p,n,r){n=$jscomp.global;g=g.split(".");for(r=0;r<g.length-1;r++){var q=g[r];if(!(q in n))return;n=n[q]}g=g[g.length-1];r=n[g];p=p(r);p!=r&&null!=p&&$jscomp.defineProperty(n,g,{configurable:!0,writable:!0,value:p})};
$jscomp.polyfillIsolated=function(g,p,n,r){var q=g.split(".");g=1===q.length;r=q[0];r=!g&&r in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var y=0;y<q.length-1;y++){var E=q[y];if(!(E in r))return;r=r[E]}q=q[q.length-1];n=$jscomp.IS_SYMBOL_NATIVE&&"es6"===n?r[q]:null;p=p(n);null!=p&&(g?$jscomp.defineProperty($jscomp.polyfills,q,{configurable:!0,writable:!0,value:p}):p!==n&&(void 0===$jscomp.propertyToPolyfillSymbol[q]&&(n=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[q]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(q):$jscomp.POLYFILL_PREFIX+n+"$"+q),$jscomp.defineProperty(r,$jscomp.propertyToPolyfillSymbol[q],{configurable:!0,writable:!0,value:p})))};$jscomp.polyfill("Array.prototype.find",function(g){return g?g:function(p,n){return $jscomp.findInternal(this,p,n).v}},"es6","es3");
(function(g){"object"==typeof exports&&"object"==typeof module?g(require("../lib/codemirror"),require("../addon/search/searchcursor"),require("../addon/edit/matchbrackets")):"function"==typeof define&&define.amd?define(["../lib/codemirror","../addon/search/searchcursor","../addon/edit/matchbrackets"],g):g(CodeMirror)})(function(g){function p(a,b){a.extendSelectionsBy(function(c){if(a.display.shift||a.doc.extend||c.empty()){var d=a.doc;c=c.head;if(0>b&&0==c.ch)var e=d.clipPos(m(c.line-1));else{var f=
d.getLine(c.line);if(0<b&&c.ch>=f.length)e=d.clipPos(m(c.line+1,0));else{d="start";for(var h=c.ch,k=h,t=0>b?0:f.length,v=0;k!=t;k+=b,v++){var w=f.charAt(0>b?k-1:k),u="_"!=w&&g.isWordChar(w)?"w":"o";"w"==u&&w.toUpperCase()==w&&(u="W");if("start"==d)"o"!=u?(d="in",e=u):h=k+b;else if("in"==d&&e!=u){"w"==e&&"W"==u&&0>b&&k--;if("W"==e&&"w"==u&&0<b)if(k==h+1){e="w";continue}else k--;break}}e=m(c.line,k)}}return e}return 0>b?c.from():c.to()})}function n(a,b){if(a.isReadOnly())return g.Pass;a.operation(function(){for(var c=
a.listSelections().length,d=[],e=-1,f=0;f<c;f++){var h=a.listSelections()[f].head;h.line<=e||(e=m(h.line+(b?0:1),0),a.replaceRange("\n",e,null,"+insertLine"),a.indentLine(e.line,null,!0),d.push({head:e,anchor:e}),e=h.line+1)}a.setSelections(d)});a.execCommand("indentAuto")}function r(a,b){var c=b.ch,d=c;for(a=a.getLine(b.line);c&&g.isWordChar(a.charAt(c-1));)--c;for(;d<a.length&&g.isWordChar(a.charAt(d));)++d;return{from:m(b.line,c),to:m(b.line,d),word:a.slice(c,d)}}function q(a,b){for(var c=a.listSelections(),
d=[],e=0;e<c.length;e++){var f=c[e],h=a.findPosV(f.anchor,b,"line",f.anchor.goalColumn),k=a.findPosV(f.head,b,"line",f.head.goalColumn);h.goalColumn=null!=f.anchor.goalColumn?f.anchor.goalColumn:a.cursorCoords(f.anchor,"div").left;k.goalColumn=null!=f.head.goalColumn?f.head.goalColumn:a.cursorCoords(f.head,"div").left;h={anchor:h,head:k};d.push(f);d.push(h)}a.setSelections(d)}function y(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++){var e=b[d],f=e.head,h=a.scanForBracket(f,-1);if(!h)return!1;
for(;;){f=a.scanForBracket(f,1);if(!f)return!1;if(f.ch=="(){}[]".charAt("(){}[]".indexOf(h.ch)+1)){var k=m(h.pos.line,h.pos.ch+1);if(0==g.cmpPos(k,e.from())&&0==g.cmpPos(f.pos,e.to())){if(h=a.scanForBracket(h.pos,-1),!h)return!1}else{c.push({anchor:k,head:f.pos});break}}f=m(f.pos.line,f.pos.ch+1)}}a.setSelections(c);return!0}function E(a){return a?/\bpunctuation\b/.test(a)?a:void 0:null}function F(a,b,c){if(a.isReadOnly())return g.Pass;for(var d=a.listSelections(),e=[],f,h=0;h<d.length;h++){var k=
d[h];if(!k.empty()){var t=k.from().line;for(k=k.to().line;h<d.length-1&&d[h+1].from().line==k;)k=d[++h].to().line;d[h].to().ch||k--;e.push(t,k)}}e.length?f=!0:e.push(a.firstLine(),a.lastLine());a.operation(function(){for(var v=[],w=0;w<e.length;w+=2){var u=e[w+1],A=m(e[w],0),D=m(u),B=a.getRange(A,D,!1);b?B.sort(function(x,C){return x<C?-c:x==C?0:c}):B.sort(function(x,C){var G=x.toUpperCase(),H=C.toUpperCase();G!=H&&(x=G,C=H);return x<C?-c:x==C?0:c});a.replaceRange(B,A,D);f&&v.push({anchor:A,head:m(u+
1,0)})}f&&a.setSelections(v,0)})}function I(a,b){a.operation(function(){for(var c=a.listSelections(),d=[],e=[],f=0;f<c.length;f++){var h=c[f];h.empty()?(d.push(f),e.push("")):e.push(b(a.getRange(h.from(),h.to())))}a.replaceSelections(e,"around","case");f=d.length-1;for(var k;0<=f;f--)h=c[d[f]],k&&0<g.cmpPos(h.head,k)||(e=r(a,h.head),k=e.from,a.replaceRange(b(e.word),e.from,e.to))})}function J(a){var b=a.getCursor("from"),c=a.getCursor("to");if(0==g.cmpPos(b,c)){var d=r(a,b);if(!d.word)return;b=d.from;
c=d.to}return{from:b,to:c,query:a.getRange(b,c),word:d}}function K(a,b){var c=J(a);if(c){var d=c.query,e=a.getSearchCursor(d,b?c.to:c.from);(b?e.findNext():e.findPrevious())?a.setSelection(e.from(),e.to()):(e=a.getSearchCursor(d,b?m(a.firstLine(),0):a.clipPos(m(a.lastLine()))),(b?e.findNext():e.findPrevious())?a.setSelection(e.from(),e.to()):c.word&&a.setSelection(c.from,c.to))}}var l=g.commands,m=g.Pos;l.goSubwordLeft=function(a){p(a,-1)};l.goSubwordRight=function(a){p(a,1)};l.scrollLineUp=function(a){var b=
a.getScrollInfo();if(!a.somethingSelected()){var c=a.lineAtHeight(b.top+b.clientHeight,"local");a.getCursor().line>=c&&a.execCommand("goLineUp")}a.scrollTo(null,b.top-a.defaultTextHeight())};l.scrollLineDown=function(a){var b=a.getScrollInfo();if(!a.somethingSelected()){var c=a.lineAtHeight(b.top,"local")+1;a.getCursor().line<=c&&a.execCommand("goLineDown")}a.scrollTo(null,b.top+a.defaultTextHeight())};l.splitSelectionByLine=function(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++)for(var e=
b[d].from(),f=b[d].to(),h=e.line;h<=f.line;++h)f.line>e.line&&h==f.line&&0==f.ch||c.push({anchor:h==e.line?e:m(h,0),head:h==f.line?f:m(h)});a.setSelections(c,0)};l.singleSelectionTop=function(a){var b=a.listSelections()[0];a.setSelection(b.anchor,b.head,{scroll:!1})};l.selectLine=function(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++){var e=b[d];c.push({anchor:m(e.from().line,0),head:m(e.to().line+1,0)})}a.setSelections(c)};l.insertLineAfter=function(a){return n(a,!1)};l.insertLineBefore=
function(a){return n(a,!0)};l.selectNextOccurrence=function(a){var b=a.getCursor("from"),c=a.getCursor("to"),d=a.state.sublimeFindFullWord==a.doc.sel;if(0==g.cmpPos(b,c)){d=r(a,b);if(!d.word)return;a.setSelection(d.from,d.to);d=!0}else{b=a.getRange(b,c);b=d?new RegExp("\\b"+b+"\\b"):b;c=a.getSearchCursor(b,c);var e=c.findNext();e||(c=a.getSearchCursor(b,m(a.firstLine(),0)),e=c.findNext());if(!(b=!e))a:{b=a.listSelections();e=c.from();for(var f=c.to(),h=0;h<b.length;h++)if(0==g.cmpPos(b[h].from(),
e)&&0==g.cmpPos(b[h].to(),f)){b=!0;break a}b=!1}if(b)return;a.addSelection(c.from(),c.to())}d&&(a.state.sublimeFindFullWord=a.doc.sel)};l.skipAndSelectNextOccurrence=function(a){var b=a.getCursor("anchor"),c=a.getCursor("head");l.selectNextOccurrence(a);0!=g.cmpPos(b,c)&&a.doc.setSelections(a.doc.listSelections().filter(function(d){return d.anchor!=b||d.head!=c}))};l.addCursorToPrevLine=function(a){q(a,-1)};l.addCursorToNextLine=function(a){q(a,1)};l.selectScope=function(a){y(a)||a.execCommand("selectAll")};
l.selectBetweenBrackets=function(a){if(!y(a))return g.Pass};l.goToBracket=function(a){a.extendSelectionsBy(function(b){var c=a.scanForBracket(b.head,1,E(a.getTokenTypeAt(b.head)));return c&&0!=g.cmpPos(c.pos,b.head)?c.pos:(c=a.scanForBracket(b.head,-1,E(a.getTokenTypeAt(m(b.head.line,b.head.ch+1)))))&&m(c.pos.line,c.pos.ch+1)||b.head})};l.swapLineUp=function(a){if(a.isReadOnly())return g.Pass;for(var b=a.listSelections(),c=[],d=a.firstLine()-1,e=[],f=0;f<b.length;f++){var h=b[f],k=h.from().line-1,
t=h.to().line;e.push({anchor:m(h.anchor.line-1,h.anchor.ch),head:m(h.head.line-1,h.head.ch)});0!=h.to().ch||h.empty()||--t;k>d?c.push(k,t):c.length&&(c[c.length-1]=t);d=t}a.operation(function(){for(var v=0;v<c.length;v+=2){var w=c[v],u=c[v+1],A=a.getLine(w);a.replaceRange("",m(w,0),m(w+1,0),"+swapLine");u>a.lastLine()?a.replaceRange("\n"+A,m(a.lastLine()),null,"+swapLine"):a.replaceRange(A+"\n",m(u,0),null,"+swapLine")}a.setSelections(e);a.scrollIntoView()})};l.swapLineDown=function(a){if(a.isReadOnly())return g.Pass;
for(var b=a.listSelections(),c=[],d=a.lastLine()+1,e=b.length-1;0<=e;e--){var f=b[e],h=f.to().line+1,k=f.from().line;0!=f.to().ch||f.empty()||h--;h<d?c.push(h,k):c.length&&(c[c.length-1]=k);d=k}a.operation(function(){for(var t=c.length-2;0<=t;t-=2){var v=c[t],w=c[t+1],u=a.getLine(v);v==a.lastLine()?a.replaceRange("",m(v-1),m(v),"+swapLine"):a.replaceRange("",m(v,0),m(v+1,0),"+swapLine");a.replaceRange(u+"\n",m(w,0),null,"+swapLine")}a.scrollIntoView()})};l.toggleCommentIndented=function(a){a.toggleComment({indent:!0})};
l.joinLines=function(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++){for(var e=b[d],f=e.from(),h=f.line,k=e.to().line;d<b.length-1&&b[d+1].from().line==k;)k=b[++d].to().line;c.push({start:h,end:k,anchor:!e.empty()&&f})}a.operation(function(){for(var t=0,v=[],w=0;w<c.length;w++){for(var u=c[w],A=u.anchor&&m(u.anchor.line-t,u.anchor.ch),D,B=u.start;B<=u.end;B++){var x=B-t;B==u.end&&(D=m(x,a.getLine(x).length+1));x<a.lastLine()&&(a.replaceRange(" ",m(x),m(x+1,/^\s*/.exec(a.getLine(x+1))[0].length)),
++t)}v.push({anchor:A||D,head:D})}a.setSelections(v,0)})};l.duplicateLine=function(a){a.operation(function(){for(var b=a.listSelections().length,c=0;c<b;c++){var d=a.listSelections()[c];d.empty()?a.replaceRange(a.getLine(d.head.line)+"\n",m(d.head.line,0)):a.replaceRange(a.getRange(d.from(),d.to()),d.from())}a.scrollIntoView()})};l.sortLines=function(a){F(a,!0,1)};l.reverseSortLines=function(a){F(a,!0,-1)};l.sortLinesInsensitive=function(a){F(a,!1,1)};l.reverseSortLinesInsensitive=function(a){F(a,
!1,-1)};l.nextBookmark=function(a){var b=a.state.sublimeBookmarks;if(b)for(;b.length;){var c=b.shift(),d=c.find();if(d)return b.push(c),a.setSelection(d.from,d.to)}};l.prevBookmark=function(a){var b=a.state.sublimeBookmarks;if(b)for(;b.length;){b.unshift(b.pop());var c=b[b.length-1].find();if(c)return a.setSelection(c.from,c.to);b.pop()}};l.toggleBookmark=function(a){for(var b=a.listSelections(),c=a.state.sublimeBookmarks||(a.state.sublimeBookmarks=[]),d=0;d<b.length;d++){for(var e=b[d].from(),f=
b[d].to(),h=b[d].empty()?a.findMarksAt(e):a.findMarks(e,f),k=0;k<h.length;k++)if(h[k].sublimeBookmark){h[k].clear();for(var t=0;t<c.length;t++)c[t]==h[k]&&c.splice(t--,1);break}k==h.length&&c.push(a.markText(e,f,{sublimeBookmark:!0,clearWhenEmpty:!1}))}};l.clearBookmarks=function(a){if(a=a.state.sublimeBookmarks)for(var b=0;b<a.length;b++)a[b].clear();a.length=0};l.selectBookmarks=function(a){var b=a.state.sublimeBookmarks,c=[];if(b)for(var d=0;d<b.length;d++){var e=b[d].find();e?c.push({anchor:e.from,
head:e.to}):b.splice(d--,0)}c.length&&a.setSelections(c,0)};l.smartBackspace=function(a){if(a.somethingSelected())return g.Pass;a.operation(function(){for(var b=a.listSelections(),c=a.getOption("indentUnit"),d=b.length-1;0<=d;d--){var e=b[d].head,f=a.getRange({line:e.line,ch:0},e),h=g.countColumn(f,null,a.getOption("tabSize")),k=a.findPosH(e,-1,"char",!1);f&&!/\S/.test(f)&&0==h%c&&(f=new m(e.line,g.findColumn(f,h-c,c)),f.ch!=e.ch&&(k=f));a.replaceRange("",k,e,"+delete")}})};l.delLineRight=function(a){a.operation(function(){for(var b=
a.listSelections(),c=b.length-1;0<=c;c--)a.replaceRange("",b[c].anchor,m(b[c].to().line),"+delete");a.scrollIntoView()})};l.upcaseAtCursor=function(a){I(a,function(b){return b.toUpperCase()})};l.downcaseAtCursor=function(a){I(a,function(b){return b.toLowerCase()})};l.setSublimeMark=function(a){a.state.sublimeMark&&a.state.sublimeMark.clear();a.state.sublimeMark=a.setBookmark(a.getCursor())};l.selectToSublimeMark=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();b&&a.setSelection(a.getCursor(),
b)};l.deleteToSublimeMark=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();if(b){var c=a.getCursor();if(0<g.cmpPos(c,b)){var d=b;b=c;c=d}a.state.sublimeKilled=a.getRange(c,b);a.replaceRange("",c,b)}};l.swapWithSublimeMark=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();b&&(a.state.sublimeMark.clear(),a.state.sublimeMark=a.setBookmark(a.getCursor()),a.setCursor(b))};l.sublimeYank=function(a){null!=a.state.sublimeKilled&&a.replaceSelection(a.state.sublimeKilled,null,
"paste")};l.showInCenter=function(a){var b=a.cursorCoords(null,"local");a.scrollTo(null,(b.top+b.bottom)/2-a.getScrollInfo().clientHeight/2)};l.findUnder=function(a){K(a,!0)};l.findUnderPrevious=function(a){K(a,!1)};l.findAllUnder=function(a){var b=J(a);if(b){for(var c=a.getSearchCursor(b.query),d=[],e=-1;c.findNext();)d.push({anchor:c.from(),head:c.to()}),c.from().line<=b.from.line&&c.from().ch<=b.from.ch&&e++;a.setSelections(d,e)}};var z=g.keyMap;z.macSublime={"Cmd-Left":"goLineStartSmart","Shift-Tab":"indentLess",
"Shift-Ctrl-K":"deleteLine","Alt-Q":"wrapLines","Ctrl-Left":"goSubwordLeft","Ctrl-Right":"goSubwordRight","Ctrl-Alt-Up":"scrollLineUp","Ctrl-Alt-Down":"scrollLineDown","Cmd-L":"selectLine","Shift-Cmd-L":"splitSelectionByLine",Esc:"singleSelectionTop","Cmd-Enter":"insertLineAfter","Shift-Cmd-Enter":"insertLineBefore","Cmd-D":"selectNextOccurrence","Shift-Cmd-Space":"selectScope","Shift-Cmd-M":"selectBetweenBrackets","Cmd-M":"goToBracket","Cmd-Ctrl-Up":"swapLineUp","Cmd-Ctrl-Down":"swapLineDown","Cmd-/":"toggleCommentIndented",
"Cmd-J":"joinLines","Shift-Cmd-D":"duplicateLine",F5:"sortLines","Shift-F5":"reverseSortLines","Cmd-F5":"sortLinesInsensitive","Shift-Cmd-F5":"reverseSortLinesInsensitive",F2:"nextBookmark","Shift-F2":"prevBookmark","Cmd-F2":"toggleBookmark","Shift-Cmd-F2":"clearBookmarks","Alt-F2":"selectBookmarks",Backspace:"smartBackspace","Cmd-K Cmd-D":"skipAndSelectNextOccurrence","Cmd-K Cmd-K":"delLineRight","Cmd-K Cmd-U":"upcaseAtCursor","Cmd-K Cmd-L":"downcaseAtCursor","Cmd-K Cmd-Space":"setSublimeMark","Cmd-K Cmd-A":"selectToSublimeMark",
"Cmd-K Cmd-W":"deleteToSublimeMark","Cmd-K Cmd-X":"swapWithSublimeMark","Cmd-K Cmd-Y":"sublimeYank","Cmd-K Cmd-C":"showInCenter","Cmd-K Cmd-G":"clearBookmarks","Cmd-K Cmd-Backspace":"delLineLeft","Cmd-K Cmd-1":"foldAll","Cmd-K Cmd-0":"unfoldAll","Cmd-K Cmd-J":"unfoldAll","Ctrl-Shift-Up":"addCursorToPrevLine","Ctrl-Shift-Down":"addCursorToNextLine","Cmd-F3":"findUnder","Shift-Cmd-F3":"findUnderPrevious","Alt-F3":"findAllUnder","Shift-Cmd-[":"fold","Shift-Cmd-]":"unfold","Cmd-I":"findIncremental","Shift-Cmd-I":"findIncrementalReverse",
"Cmd-H":"replace",F3:"findNext","Shift-F3":"findPrev",fallthrough:"macDefault"};g.normalizeKeyMap(z.macSublime);z.pcSublime={"Shift-Tab":"indentLess","Shift-Ctrl-K":"deleteLine","Alt-Q":"wrapLines","Ctrl-T":"transposeChars","Alt-Left":"goSubwordLeft","Alt-Right":"goSubwordRight","Ctrl-Up":"scrollLineUp","Ctrl-Down":"scrollLineDown","Ctrl-L":"selectLine","Shift-Ctrl-L":"splitSelectionByLine",Esc:"singleSelectionTop","Ctrl-Enter":"insertLineAfter","Shift-Ctrl-Enter":"insertLineBefore","Ctrl-D":"selectNextOccurrence",
"Shift-Ctrl-Space":"selectScope","Shift-Ctrl-M":"selectBetweenBrackets","Ctrl-M":"goToBracket","Shift-Ctrl-Up":"swapLineUp","Shift-Ctrl-Down":"swapLineDown","Ctrl-/":"toggleCommentIndented","Ctrl-J":"joinLines","Shift-Ctrl-D":"duplicateLine",F9:"sortLines","Shift-F9":"reverseSortLines","Ctrl-F9":"sortLinesInsensitive","Shift-Ctrl-F9":"reverseSortLinesInsensitive",F2:"nextBookmark","Shift-F2":"prevBookmark","Ctrl-F2":"toggleBookmark","Shift-Ctrl-F2":"clearBookmarks","Alt-F2":"selectBookmarks",Backspace:"smartBackspace",
"Ctrl-K Ctrl-D":"skipAndSelectNextOccurrence","Ctrl-K Ctrl-K":"delLineRight","Ctrl-K Ctrl-U":"upcaseAtCursor","Ctrl-K Ctrl-L":"downcaseAtCursor","Ctrl-K Ctrl-Space":"setSublimeMark","Ctrl-K Ctrl-A":"selectToSublimeMark","Ctrl-K Ctrl-W":"deleteToSublimeMark","Ctrl-K Ctrl-X":"swapWithSublimeMark","Ctrl-K Ctrl-Y":"sublimeYank","Ctrl-K Ctrl-C":"showInCenter","Ctrl-K Ctrl-G":"clearBookmarks","Ctrl-K Ctrl-Backspace":"delLineLeft","Ctrl-K Ctrl-1":"foldAll","Ctrl-K Ctrl-0":"unfoldAll","Ctrl-K Ctrl-J":"unfoldAll",
"Ctrl-Alt-Up":"addCursorToPrevLine","Ctrl-Alt-Down":"addCursorToNextLine","Ctrl-F3":"findUnder","Shift-Ctrl-F3":"findUnderPrevious","Alt-F3":"findAllUnder","Shift-Ctrl-[":"fold","Shift-Ctrl-]":"unfold","Ctrl-I":"findIncremental","Shift-Ctrl-I":"findIncrementalReverse","Ctrl-H":"replace",F3:"findNext","Shift-F3":"findPrev",fallthrough:"pcDefault"};g.normalizeKeyMap(z.pcSublime);z.sublime=z.default==z.macDefault?z.macSublime:z.pcSublime});
