(function(f){"object"==typeof exports&&"object"==typeof module?f(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],f):f(CodeMirror)})(function(f){f.defineMode("gas",function(g,m){function q(b){h="@";n.syntax="builtin";a.r0="variable";a.r1="variable";a.r2="variable";a.r3="variable";a.r4="variable";a.r5="variable";a.r6="variable";a.r7="variable";a.r8="variable";a.r9="variable";a.r10="variable";a.r11="variable";a.r12="variable";a.sp="variable-2";a.lr=
"variable-2";a.pc="variable-2";a.r13=a.sp;a.r14=a.lr;a.r15=a.pc;k.push(function(d,e){if("#"===d)return e.eatWhile(/\w/),"number"})}function p(b,d){for(var e=!1,c;null!=(c=b.next());){if("/"===c&&e){d.tokenize=null;break}e="*"===c}return"comment"}var k=[],h="",n={".abort":"builtin",".align":"builtin",".altmacro":"builtin",".ascii":"builtin",".asciz":"builtin",".balign":"builtin",".balignw":"builtin",".balignl":"builtin",".bundle_align_mode":"builtin",".bundle_lock":"builtin",".bundle_unlock":"builtin",
".byte":"builtin",".cfi_startproc":"builtin",".comm":"builtin",".data":"builtin",".def":"builtin",".desc":"builtin",".dim":"builtin",".double":"builtin",".eject":"builtin",".else":"builtin",".elseif":"builtin",".end":"builtin",".endef":"builtin",".endfunc":"builtin",".endif":"builtin",".equ":"builtin",".equiv":"builtin",".eqv":"builtin",".err":"builtin",".error":"builtin",".exitm":"builtin",".extern":"builtin",".fail":"builtin",".file":"builtin",".fill":"builtin",".float":"builtin",".func":"builtin",
".global":"builtin",".gnu_attribute":"builtin",".hidden":"builtin",".hword":"builtin",".ident":"builtin",".if":"builtin",".incbin":"builtin",".include":"builtin",".int":"builtin",".internal":"builtin",".irp":"builtin",".irpc":"builtin",".lcomm":"builtin",".lflags":"builtin",".line":"builtin",".linkonce":"builtin",".list":"builtin",".ln":"builtin",".loc":"builtin",".loc_mark_labels":"builtin",".local":"builtin",".long":"builtin",".macro":"builtin",".mri":"builtin",".noaltmacro":"builtin",".nolist":"builtin",
".octa":"builtin",".offset":"builtin",".org":"builtin",".p2align":"builtin",".popsection":"builtin",".previous":"builtin",".print":"builtin",".protected":"builtin",".psize":"builtin",".purgem":"builtin",".pushsection":"builtin",".quad":"builtin",".reloc":"builtin",".rept":"builtin",".sbttl":"builtin",".scl":"builtin",".section":"builtin",".set":"builtin",".short":"builtin",".single":"builtin",".size":"builtin",".skip":"builtin",".sleb128":"builtin",".space":"builtin",".stab":"builtin",".string":"builtin",
".struct":"builtin",".subsection":"builtin",".symver":"builtin",".tag":"builtin",".text":"builtin",".title":"builtin",".type":"builtin",".uleb128":"builtin",".val":"builtin",".version":"builtin",".vtable_entry":"builtin",".vtable_inherit":"builtin",".warning":"builtin",".weak":"builtin",".weakref":"builtin",".word":"builtin"},a={};g=(m.architecture||"x86").toLowerCase();"x86"===g?(h="#",a.al="variable",a.ah="variable",a.ax="variable",a.eax="variable-2",a.rax="variable-3",a.bl="variable",a.bh="variable",
a.bx="variable",a.ebx="variable-2",a.rbx="variable-3",a.cl="variable",a.ch="variable",a.cx="variable",a.ecx="variable-2",a.rcx="variable-3",a.dl="variable",a.dh="variable",a.dx="variable",a.edx="variable-2",a.rdx="variable-3",a.si="variable",a.esi="variable-2",a.rsi="variable-3",a.di="variable",a.edi="variable-2",a.rdi="variable-3",a.sp="variable",a.esp="variable-2",a.rsp="variable-3",a.bp="variable",a.ebp="variable-2",a.rbp="variable-3",a.ip="variable",a.eip="variable-2",a.rip="variable-3",a.cs=
"keyword",a.ds="keyword",a.ss="keyword",a.es="keyword",a.fs="keyword",a.gs="keyword"):"arm"!==g&&"armv6"!==g||q(m);return{startState:function(){return{tokenize:null}},token:function(b,d){if(d.tokenize)return d.tokenize(b,d);if(b.eatSpace())return null;var e,c=b.next();if("/"===c&&b.eat("*"))return d.tokenize=p,p(b,d);if(c===h)return b.skipToEnd(),"comment";if('"'===c){a:for(d=!1;null!=(e=b.next());){if('"'===e&&!d)break a;d=!d&&"\\"===e}return"string"}if("."===c)return b.eatWhile(/\w/),b=b.current().toLowerCase(),
(e=n[b])||null;if("="===c)return b.eatWhile(/\w/),"tag";if("{"===c||"}"===c)return"bracket";if(/\d/.test(c)){if("0"===c&&b.eat("x"))return b.eatWhile(/[0-9a-fA-F]/),"number";b.eatWhile(/\d/);return"number"}if(/\w/.test(c)){b.eatWhile(/\w/);if(b.eat(":"))return"tag";b=b.current().toLowerCase();return(e=a[b])||null}for(var l=0;l<k.length;l++)if(e=k[l](c,b,d))return e},lineComment:h,blockCommentStart:"/*",blockCommentEnd:"*/"}})});
