name: github pages dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-repo

      - name: Setup Dart SDK
        uses: ./.github/actions/setup-dart

      - name: Install dependencies
        run: dart pub get

      - name: Build generated files for sub-packages
        run: |
          cd scadnano_state_actions && dart run build_runner build --delete-conflicting-outputs && cd ..
          cd scadnano_reducers && dart run build_runner build --delete-conflicting-outputs && cd ..

      - name: Install webdev
        run: dart pub global activate webdev

      - name: Build into gh-pages repo
        run: dart pub global run webdev build -o web:gh-pages-repo/dev

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-repo
