name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-18.04

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@v1.1.0"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build [TODO: Replace label and number with version number]"
          files: |
            LICENSE.txt
