name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  create-release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build [TODO: Replace label and title with version number]"
          files: |
            LICENSE.txt

  upload-artifacts:
    name: Build on ${{ matrix.os }}
    needs: [ create-release ]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            npm_command: npm run build:lin
          - os: windows-latest
            npm_command: npm run build:win
          - os: macos-latest
            npm_command: npm run build:mac

    runs-on: ${{ matrix.os }}
    steps:
      # Setup Builder
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.8

      - name: Install ImageMagick
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update && sudo apt-get install -y imagemagick libfuse2
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install imagemagick
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install imagemagick -y
          fi

      - name: Install NodeJS Dependencies
        working-directory: ./standalone
        run: npm install

      - name: Generate Icons
        working-directory: ./standalone
        shell: bash
        run: |
          chmod +x ./generate-icons.sh
          ./generate-icons.sh ../web/images/origami-icon-thin-seam.png

      - name: Run build
        run: ${{ matrix.npm_command }}

      # Upload the generated artifacts (pattern: scadnano*.<ext>)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: "standalone/dist/scadnano*.*"

  attach-to-release:
    name: Attach artifacts to release
    runs-on: ubuntu-latest
    needs: [upload-artifacts, create-release]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: ./release-files/**/scadnano*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
